### ISSUE TITLE
Fastlane sourcemaps Integration

### ISSUE THREAD

**Issue by dwilt** [bugsnag/bugsnag-js#1037]
### Description
Currently, there is a fastlane plugin to upload the native stuff for sourcemaps but nothing for JS. [The docs](https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/#uploading-source-maps) are helpful but it would be really helpful to have this automated (since a React Native project setup is a fixed directory structure).

**Describe the solution you'd like**
A plugin that would handle all of this since it can be automated and can then be part of the Fastlane process (thus, easily come after the `increment_build_number` command).

**Describe alternatives you've considered**
We're having to write our own custom commands for Fastlane via a shell command.

**Additional context**
Add any other context about the feature request here.

**Comment by johnkiely1** [comment]
This has been transferred to the bugsnag-js repo as the Bugsnag react native library is now part of this repository (as of v7.3).

**Comment by johnkiely1** [comment]
Hi all,

We have now released our new source mapping tool and cli which aims to automate and simplify the whole process for react native. You can find details of how to use the cli to upload source maps in our documentation here: https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#automatic-setup. This was released in [v7.6.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.6.0) of the @bugsnag/react-native library so you would need to upgrade to this in order to use it.

It's worth noting that if you have already configured Bugsnag within your app you should use `bugsnag-react-native-cli automate-symbolication` as per the documentation. `init` should only be used for new project integrations with Bugsnag. 

The source map upload tool itself can also be used to upload source maps manually, the documentation here https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/ has been updated to use the new tool.

**Comment by alxvallejo** [comment]
Thanks @johnkiely1 . My only confusion here is around the path to the output sourcemap file:

`export EXTRA_PACKAGER_ARGS="--sourcemap-output $CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH/main.jsbundle.map"`

I'm not exactly sure where this is pointing, but this fails on my native build, saying the file does not exist. Shouldn't each of those files live within either an ios or android directly? 

Even after prefixing my bundle with `ios` it still fails on the build saying the file cannot be found.

**Comment by xander-jones** [comment]
Hey @alxvallejo, I suspect this is due to a space in your path to your build folders. In Xcode, if you go to Xcode -> Preferences -> Locations you can see where your Derived Data folder is (for Debug/Release builds), and where your Archive builds go to, for example:
![image](https://user-images.githubusercontent.com/9535852/107064117-13a0d580-67d3-11eb-90e0-634406c923f5.png)
This is a known issue at the moment, we're looking into a fix for this. But in the meantime, if there are spaces in your path, removing them will fix this issue for you.
