### ISSUE TITLE
JavaScript object expected thrown from inside Bugsnag notifier?

### ISSUE THREAD

**Issue by adunkman** [bugsnag/bugsnag-js#105]
We’re seeing a consistent low-volume stream of errors come in from IE 10 and 11, and from the stack, it appears to be coming from Bugsnag itself (but it’s hard to tell for sure, since there’s so little information provided — only one frame in the trace).

Here’s the raw trace:

```
Error JavaScript object expected
    https://[redacted].harvestapp.com/assets/web_timesheet2-80a7d003a062a3d24384e0c0e4ebc022.js:1:244 t.bugsnag
```

Our source is minified, but the line given in Bugsnag is [this block of code](https://github.com/bugsnag/bugsnag-js/blob/cf1bfd2025e5ce042bffb8d125b3d6d938912b47/src/bugsnag.js#L126-L141):

```javascript
if (options && options.eventHandler) {
  lastEvent = event;
}
lastScript = currentScript;

// We set shouldCatch to false on IE < 10 because catching the error ruins the file/line as reported in window.onerror,
// We set shouldCatch to false on Chrome/Safari because it interferes with "break on unhandled exception"
// All other browsers need shouldCatch to be true, as they don't pass the exception object to window.onerror
if (shouldCatch) {
  try {
    return _super.apply(this, arguments);
  } catch (e) {
    // We do this rather than stashing treating the error like lastEvent
    // because in FF 26 onerror is not called for synthesized event handlers.
    if (getSetting("autoNotify", true)) {
      self.notifyException(e, null, null, "error"); 
```

Here‘s [the error in our Bugsnag account](https://bugsnag.com/harvest/harvestapp-js/errors/54ff8043ecd293a301e8594c). We’re sort of ¯\\\_(ツ)\_/¯ with ideas.

Seen anything like this before? I assume that if it’s indeed an issue in the notifier, that it’d be present on other accounts for IE 10 and 11.

**Comment by ConradIrwin** [comment]
Hey @adunkman,

This has been reported before, but I was unable to figure out the problem. Before the stack-trace was from this line:

`    return _super.apply(this, arguments);`

As far as I can tell, _super must be an object, this must be an object, and arguments must be an object.

My best hypothesis is that the callback is crashing, and the stacktrace is truncated for an unknown reason (perhaps it's a native method, or it's been inlined?). What would be helpful is if we knew what the value of `_super` was when this crash happens (so that we can have a look at the event handler).

Happy to explore other ideas if you have them.

**Comment by eanakashima** [comment]
We've made some major changes to the notifier since this was opened, and haven't heard any recent reports like this, so I'm going to call this closed for now. Feel free to open a new issue if you hear of more reports or find a way to reproduce. Thanks.
