### ISSUE TITLE
[Vue plugin] Session is reloaded on every route change/navigation

### ISSUE THREAD

**Issue by szepeviktor** [bugsnag/bugsnag-js#1071]
![kép](https://user-images.githubusercontent.com/952007/94257462-a0857980-ff2b-11ea-9b7f-fbe6ee99d9e1.png)

See for yourself in our app: https://app.megmerettetes.hu/
If you navigate by clicking the links you get a new session every time.

```js
SetupAxios()

new Vue({
  router,
  store,
  beforeCreate () {
    if (process.env.BUGSNAG_API_KEY) {
      Bugsnag.start({
        apiKey: process.env.BUGSNAG_API_KEY,
        plugins: [new BugsnagPluginVue()]
      })
    }
  },
  created () {
    if (process.env.BUGSNAG_API_KEY) Bugsnag.getPlugin('vue').installVueErrorHandler(Vue)
  },
  render: h => h(App)
}).$mount('#app')
```

How to reduce sessions to one?
Please advise.

**Comment by xander-jones** [comment]
Hey @szepeviktor, if using auto-capture sessions, we capture capture a session each time:
* the page loads, or
* the URL changes via `history.pushState()` or `history.replaceState()`
So, this looks to be inline with the expected behaviour.

However, you don't have to use sessions in this way. You can manually set up how you want to capture sessions. Start by disabling automatic sessions in your config:

```js
Bugsnag.start({
  autoTrackSessions: false
})
```

Then, use the following to `start`, `pause`, and `resume` a session:

```js
Bugsnag.startSession()
Bugsnag.pauseSession()
Bugsnag.resumeSession()
```

References:
* Standard behaviour: https://docs.bugsnag.com/platforms/javascript/vue/#session-tracking
* Auto track sessions: https://docs.bugsnag.com/platforms/javascript/vue/configuration-options/#autotracksessions
* Manually capture sessions: https://docs.bugsnag.com/platforms/javascript/vue/capturing-sessions/

Let us know if you have any questions on using sessions. You can also write to us at support@bugsnag.com

**Comment by szepeviktor** [comment]
You are very kind.
