### ISSUE TITLE
Ignore react-dom in stacktrace

### ISSUE THREAD

**Issue by simkessy** [bugsnag/bugsnag-js#1085]
Is it possible to ignore react-dom in the stack trace? 

![image](https://user-images.githubusercontent.com/5871660/94890663-b7006900-0434-11eb-8daa-2bc69817ab41.png)

**Comment by mattdyoung** [comment]
Hi @simkessy 

Yes, you're able to modify the stacktrace in the error report before it's sent to Bugsnag by configuring an `onError` callback as described here:
https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#updating-events-using-callbacks

The `stacktrace` object within the error report is described here:
https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#errors
so you could either remove and stackframes with react-dom in the `file` or better, set `inProject = false` on these frames so that they're hidden by default in the Bugsnag dashboard and not used for error grouping but can still be displayed by clicking 'Full trace'.

If you have any issues getting this setup please contact support@bugsnag.com with the code of your `onError` callback and a link to the resulting error in your dashboard and we can help troubleshoot.
