### ISSUE TITLE
How to set option on react native

### ISSUE THREAD

**Issue by ardyfeb** [bugsnag/bugsnag-js#1101]
Bugsnag doesnt allow to set option on `.start` due typescript type, the only one allowed option is `codeBundleId`
![Screenshot_20201019_024632](https://user-images.githubusercontent.com/30074366/96378411-edb8dc00-11b5-11eb-9410-47c3c3d87c32.png)

**Comment by johnkiely1** [comment]
Hi @ardyfeb,

It is no longer possible to set these option via the JS layer configuration.

As part of the react native library refresh, which was moved to the bugsnag-js repo as of v7.3, there were a large number of changes made. One of these changes the configuration process such that the majority of the options must now be set in the respective native layers. There are a few options which such as `codeBundleId` or `context` which are still configurable via the JS layer but the options that you are using must now be set in the respective native layers rather than the JS layer. This change was necessary in order to ensure that the Bugsnag client is instantiated early enough in the process to capture errors in native layers that occur before the JS layer has loaded. Additionally some of the configuration options were renamed to bring them more in line with configuration options for the Bugsnag libraries for other platforms.

Please see the following documentation for the relevant options:
autoNotify --> [autoDetectErrors](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#autodetecterrors)
[releaseStage](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#releasestage) 
notifyReleaseStages --> [enabledReleaseStage](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-
options/#enabledreleasestages) 

There is also an [upgrade guide](https://github.com/bugsnag/bugsnag-js/blob/next/UPGRADING.md) which describes all of the changes in more detail.

**Comment by ardyfeb** [comment]
Thanks @johnkiely1, i moving all configuration to each platform native code
