### ISSUE TITLE
[React Native] bundleRelease fails on task :app:uploadBugsnagReleaseSourceMaps

### ISSUE THREAD

**Issue by Andarius** [bugsnag/bugsnag-js#1171]
### Describe the bug

When running `./gradlew bundleRelease`, the job fails.

**Note**: what's weird is that it was working untill yesterday, and without any changes it started failing with:
 ```
> Task :app:bugsnagReleaseReleaseTask FAILED
Bugsnag: Uploading to Releases API
{"errors":["API key not recognised: @string/BUGSNAG_ID"],"status":"error"}

```
So I replaced the corresponding field with the corresponding value and got the next error.

### Environment
* Bugsnag version: 7.5.3
* Device (e.g. iphonex): OnePlus 5T

### Example code snippet

```
./gradlew bundleRelease
```

Throws the following error.

```
> Task :app:uploadBugsnagReleaseSourceMaps FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:uploadBugsnagReleaseSourceMaps' (type 'BugsnagUploadJsSourceMapTaskGradle53Plus').
> File '/project/node_modules/@bugsnag/source-maps/bin/cli' specified for property 'bugsnagSourceMaps' does not exist.
```

**Comment by fractalwrench** [comment]
Hi @Andarius - this was caused by an alpha release of the plugin ([v5.5.0alpha01](https://github.com/bugsnag/bugsnag-android-gradle-plugin/releases/tag/v5.5.0-alpha01)), which was used in your build due to the use of a wildcard dependency version. Wildcard dependency versions look like this:

```
classpath "com.bugsnag:bugsnag-android-gradle-plugin:5.+"
```

We've released `v5.6.0` of the plugin which will prevent the issue from happening - you could also pin the dependency to a specific version which would avoid any possibility of similar issues occurring:

```
classpath "com.bugsnag:bugsnag-android-gradle-plugin:5.6.0"
```

**Comment by Andarius** [comment]
Thanks a lot for the quick answer ! Is there a way to specify only the latest stable version ? Like 5.+@stable ?

**Comment by fractalwrench** [comment]
@Andarius Gradle does allow for [locking dependency versions](https://docs.gradle.org/current/userguide/dependency_locking.html) which might be able to achieve what you're after. Otherwise I'd recommend just pinning the latest stable version. There are some useful plugins such as [this one](https://github.com/ben-manes/gradle-versions-plugin) which can help with checking for updates on pinned dependencies.
