### ISSUE TITLE
Bugsnag cannot initialize synchronously when running in the remote debugger.

### ISSUE THREAD

**Issue by cohen72** [bugsnag/bugsnag-js#1190]
I've successfully migrated to the react native latest version, and iOS is running, but Android is getting stuck, and won't pass the splash screen.

When remote debugging, I see the following warning:
```
Bugsnag cannot initialize synchronously when running in the remote debugger.

Error reporting is still supported, but synchronous calls afted Bugsnag.start() will no-op. This means Bugsnag.leaveBreadcrumb(), Bugsnag.setUser() and all other methods will only begin to work after a short delay.

This only affects the remote debugger. Execution of JS in the normal way (on the device) is not affected.
```

And below that an unhandled promise:
```
Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'NativeClient.configureAsync')
```

I have stopped remote debugging, however Android is still getting stuck when hitting `Bugsnag.start()` on the javascript side.

I have not found anything within issues here, or on google that help give me a clue as to why it occurs. Thanks!

Not sure if it's connected, but I'm using React Native Navigation from Wix.com which perhaps affects the launch of the app in which the `Bugsnag.start(this);` within `MainApplication.java`'s `onCreate` is not being called at the right time, and there's some sort of race condition ...

**Comment by mattdyoung** [comment]
Hi @cohen72 

There are some known issues when a debugger is attached which we are working to resolve so that functionality degrades more gracefully when it's not possible to make synchronous calls.

What's the failure you see when launching without a debugger? Are you able to share full details of the code used to initialize Bugsnag and where you're initializing this in your app so we can try to reproduce what you're seeing? Feel free to email support@bugsnag.com if you'd rather not share the code here.

**Comment by mattdyoung** [comment]
In addition to the above questions, I'd be interested if you're still seeing the issue following our changes in [v7.6.1](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.6.1)?

**Comment by mattdyoung** [comment]
Closing for now due to no response, but please do share full details if you're still seeing issues in the latest version.
