### ISSUE TITLE
Bugsnag.notifyException severity defaults to warning

### ISSUE THREAD

**Issue by Dmitry9999** [bugsnag/bugsnag-js#120]
`Bugsnag.notifyException()` severity defaults to `warning`. It caused confusion while seeing errors in https://bugsnag.com and filtering them by severity. Especially confusing when other warnings are logged and should be differentiated from app exceptions. Now it requires writing your own functions for correct logging.
Should severity be `error` by default?

**Comment by eanakashima** [comment]
@Dmitry9999 Thanks for the feedback, and sorry to hear this was confusing. I think the idea behind having `warning` as the default was that you're likely to call notifyException in the case of a [caught exception](https://github.com/bugsnag/bugsnag-js#sending-caught-exceptions-or-custom-errors). In that case, you're likely already doing something to recover from the error, so it may be less serious than an uncaught exception. If you use the default [autonotify](https://github.com/bugsnag/bugsnag-js#autonotify) behavior to automatically send uncaught exceptions, those will have severity `error`, since it's likely that you didn't expect them and the app probably didn't do anything to recover.

I don't think we'd want to change the default severity in the current major version of bugsnag-js, since it could be such a big change for current customers, but we can keep it in mind for the future.
