### ISSUE TITLE
AnrPlugin.kt:-2 - com.bugsnag.android.AnrPlugin.enableAnrReporting

### ISSUE THREAD

**Issue by fabriziobertoglio1987** [bugsnag/bugsnag-js#1238]
### Describe the bug

`enableAnrReporting(true)` triggers the following Error in Production at the [following line](https://github.com/bugsnag/bugsnag-android/blob/6e4e0ae86df24c2599d918a10ef5dba14b117ea1/bugsnag-plugin-android-anr/src/main/java/com/bugsnag/android/AnrPlugin.kt#L34).

```
java.lang.UnsatisfiedLinkError: No implementation found for void com.bugsnag.android.AnrPlugin.enableAnrReporting(boolean) (tried Java_com_bugsnag_android_AnrPlugin_enableAnrReporting and Java_com_bugsnag_android_AnrPlugin_enableAnrReporting__Z)
```

### Environment
The error was experienced on the following environment, we are upgrading the denpency and we will update this issue:
* Bugsnag version: @bugsnag/react-native@7.5.3
* Browser framework version (if any):
    * React: react-native@0.62.2 react@16.11.0:
* Device (e.g. iphonex): Pixel 3a API 28

### Example Repo 

- [ ] Create a minimal repository that can reproduce the issue
- [ ] Link to it here:

<details><summary>Error messages:</summary>

<img src="https://user-images.githubusercontent.com/24992535/104483858-dfb60400-55c8-11eb-9d26-8ab8b7fe736d.png" />

</details>

**Comment by johnkiely1** [comment]
Hi @fabriziobertoglio1987.

I believe this this error will be thrown due to the android native library loader being somewhat unreliable in certain conditions. You can try using Relinker to manually load the library before calling `Bugsnag.start()`. Instructions on how to do that can be found here:  https://docs.bugsnag.com/platforms/android/faq/#what-are-anrlinkerror-and-ndklinkerrors
