### ISSUE TITLE
Little change to make it possible to load async or with script loaders

### ISSUE THREAD

**Issue by gil** [bugsnag/bugsnag-js#125]
Hi guys, I've tried to load Bugsnag script asynchronously and with script loaders (head.js and $script) and it always informed me that my apiKey was invalid. I've debugged and found this:

https://github.com/bugsnag/bugsnag-js/blob/b70cd8de3c503f6ec6ebc9fc0d415ef50c6a0e28/src/bugsnag.js#L231-L232

This two lines consider that the script will always be the last one on the page, but this will only be true if you're loading it synchronously.

Maybe it should find the script based on "src", matching for "bugsnag". What you guys think? I can send a PR later with a possible solution :]

**Comment by gil** [comment]
Another possible solution would be asking for people to add something like:

```
<script src="" data-bugsnag />
```

Looking for this data attribute and fallback to the last script on page, when it wasn't found.

**Comment by jacobmarshall** [comment]
I really like the second idea, as the first is just asking for trouble.

Good idea!
On Thu, 19 Nov 2015 at 1:59 AM André Gil <notifications@github.com> wrote:

> Another possible solution would be asking for people to add something like:
>
> <script src="" data-bugsnag />
>
> Looking for this data attribute and fallback to the last script on page,
> when it wasn't found.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bugsnag/bugsnag-js/issues/125#issuecomment-157704443>.
>
-- 
Regards,
Jacob Marshall

*Email:* jacob@manage.net.nz
*Phone:* (+64) 21 026 940 83

**Comment by kattrali** [comment]
@gil Thank you for the report! This is definitely a problem which could be solved by making the script detection more robust. 

> Maybe it should find the script based on "src", matching for "bugsnag".

This could prove brittle with more than one bugsnag script on the page, or otherwise a time consuming search.

> Another possible solution would be asking for people to add something like:
>
> ```
> <script src="" data-bugsnag />
> ```
> Looking for this data attribute and fallback to the last script on page, when it wasn't found.

If we take into account that bugsnag-js [supports a lot of browsers and versions](https://bugsnag.com/docs/notifiers/js#browser-support) and [data-* attribute support is only universal for the latest versions of browsers](http://caniuse.com/#feat=dataset), I think that with the fallback it should provide a better experience for users on newer browsers.

We can discuss finer details of the implementation over a PR though! :+1: Thanks!

**Comment by ConradIrwin** [comment]
This sounds like a good idea, but there are a few things to be aware of with loading the current version of Bugsnag.js asynchronously:

In order to get good debugging information for all errors, Bugsnag should be loaded synchronously, but this is only required for "medium-old" browsers (those that fail this check: https://github.com/bugsnag/bugsnag-js/blob/master/src/bugsnag.js#L541, IE 8-10 and Firefox 3-30, safari 7, for older-still browsers there's typically no way at all of getting this information). This is necessary because it's not possible to (in IE/Safari: get a correct stacktrace from those browsers in `window.onerror`, in Firefox: get a column number in `window.onerror` which is needed to group exceptions better), so we override `addEventListener` and friends to add a try-catch block for old browsers.

Thus if your code loads before bugsnag on old browsers, you will miss some error reports because there's not enough information, and get no stack traces for others. (You'll also miss errors that happened before Bugsnag loads, but that's probably fine).

If async loading is important to you (and you care about the old browsers) it would be better to minify bugsnag-js into your own code, and ensure Bugsnag is loaded right at the start.

All of that said, I support making the change to make this work better, because for some people loading Bugsnag async from CDN is a reasonable trade-off.

**Comment by kattrali** [comment]
That makes sense, and helps a good deal, thanks @ConradIrwin. It sounds like we could improve the current implementation and thoroughly document the caveats and process for effectively loading Bugsnag.js asynchronously. If I understood this completely, the caveats should be:

* Synchronous loading is the only way to ensure that all errors are caught
* Any code loaded before Bugsnag on older browsers can result in error report loss due to missing information and/or stack traces
* If library users want to load Bugsnag asynchronously and support older browsers, the best experience would be to minify Bugsnag and load it before their code in their applications

Does that cover everything?

**Comment by gaye** [comment]
+1

**Comment by eanakashima** [comment]
We've updated our docs with suggestions for async loading in the bugsnag-js [FAQ](https://docs.bugsnag.com/platforms/browsers/faq/#can-i-load-bugsnag-async), which should help address this for now. Support for using a data-attribute might be a nice thing to consider for the future though.
