### ISSUE TITLE
[React Native] Could not find com.bugsnag:bugsnag-android-core

### ISSUE THREAD

**Issue by Andarius** [bugsnag/bugsnag-js#1255]
### Describe the bug

When running `npx react-native run-android`, the job fails.

 ```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not find com.bugsnag:bugsnag-android-core:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-android:5.5.1
   > Could not find com.bugsnag:bugsnag-plugin-android-anr:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-android:5.5.1
   > Could not find com.bugsnag:bugsnag-plugin-android-ndk:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-android:5.5.1
   > Could not find com.bugsnag:bugsnag-android-core:5.5.1.
     Required by:
         project :app > com.bugsnag:bugsnag-plugin-react-native:5.2.3-react-native
```

### Environment
* Bugsnag version: 7.5.3
* Device (e.g. iphonex): OnePlus 5T

### Example code snippet

Just run 
```
npx react-native run-android
```

**Comment by fractalwrench** [comment]
Thanks for getting in touch @Andarius this is an intermittent issue that has been caused by some downtime at [Sonatype](https://status.maven.org/) that happened in the middle of our Android publishing process. This should be resolved as soon as we're able to publish to Sonatype again.

In the meantime as a workaround would you be able to confirm whether your [app/build.gradle](https://github.com/bugsnag/bugsnag-js/blob/next/examples/reactnative/rn063example/android/app/build.gradle#L184) file contains the following dependency, or anything similar looking?

```
dependencies {
    implementation "com.bugsnag:bugsnag-android:+"
}
```

If it does, we'd recommend that you pin it to a specific version, which should resolve the issue:

```
dependencies {
    implementation "com.bugsnag:bugsnag-android:5.5.0"
}
```

**Comment by Andarius** [comment]
Thanks @fractalwrench  for the quick answer.
Indeed, I already had  `classpath "com.bugsnag:bugsnag-android-gradle-plugin:5.6.0"`in  _build.gradle_ but still `implementation "com.bugsnag:bugsnag-android:5.+"` in my _app/build.gradle_. 
That fixed it thanks !

**Comment by johnkiely1** [comment]
Hi @Andarius,

Just to let you know we have been able to publish to Sonatype, so the original issue should now be resolved.
