### ISSUE TITLE
automate-symbolication: Option to fail silently?

### ISSUE THREAD

**Issue by cristianoccazinsp** [bugsnag/bugsnag-js#1260]
I'm trying to use `automate-symbolication`, or automatically uploading source maps for a react native project. However, looks like failing to upload to bugsnag (due to timeouts or spotty internet) is causing the entire build step to fail.

I would like to know, or request, if it would be possible to only upload source maps if a "production" build is being generated (that is, for iOS only do this when archiving, and for Android only when running `./gradlew bundleProdRelease`). Otherwise, this is very inconvenient since installing "production" builds into the device directly from XCode or ADB will also trigger a source map upload.

**Comment by davidpaulhunt** [comment]
We just upgraded to use automatic symbolication in our RN project and would like this option, too. Otherwise, we're going to be forced to revert to manual uploads.

Side note: there's a bug in RN's bundle step where passing a source map file path with any whitespace causes the source map to NOT be generated, FYI in case anyone runs into silent failures. There's an open issue about it [here](https://github.com/philipshurpik/react-native-source-maps/issues/4#issuecomment-524201077).

**Comment by xander-jones** [comment]
Our CLI is currently designed to target all release builds as users may wish to check their Bugsnag integration locally on a release build that is not distributed.

If you wish to reduce the build targets with uploads enabled, we suggest the following customizations:

For **Android**, you can disable the plugin for these variants using the `variantFilter` API, which is described in our [integration instructions](https://docs.bugsnag.com/build-integrations/gradle/#installation). The `variantFilter` API could also be conditionally enabled through the use of environment variables if you only want to upload mapping files on CI, for example.

For **iOS**, you can add some logic to the build phase added by our CLI to skip the upload if not archiving:

```sh
if [ "$DEPLOYMENT_LOCATION" != "YES" ]; then
 echo "Skipping source map upload for developer build."
 exit 0
fi
```

There's also an `ACTION` environment variable that is `build` for builds and `install` when building for archive that could be used to condition the upload.

**Comment by cristianoccazinsp** [comment]
@xander-jones  that's very helpful! Can you elaborate a bit more on the iOS implementation? I'm unsure what the `DEPLOYMENT_LOCATION` and `ACTION` variables are.

Basically, how do I know if it is a bundle/archive operation, or a "run/install" operation?

**Comment by xander-jones** [comment]
Hey @cristianoccazinsp,

> I'm unsure what the `DEPLOYMENT_LOCATION` and `ACTION` variables are.

These are environment variables which are generated by Xcode when you run a build. They can be accessed by the build phase scripts at build-time which will allow you to know what kind of build is happening. If `ACTION` is equal to `build`, it's a debug or release build, if it's set to `install` it's building for an archive.

Unfortunately, there's no particularly good reference for these environment variables from Apple as far as I know – other than [this resource](https://gist.github.com/gdavis/6670468), which gives some examples for each of the exported environment variables.

You can output all of your environment variables in a build by adding a simple build phase script as follows to your Xcode build phases if you want to test out what the env variables look like for different build types:
* Shell: /bin/sh​
* Script: export​
* Ensure "Show environment variables in build log" is selected.
![image](https://user-images.githubusercontent.com/9535852/105882229-51e10c80-5ffd-11eb-997f-bb8364836ac1.png)


> what's the difference between the `enabled` and `uploadReactNativeMappings` flags?

`bugsnag.uploadReactNativeMappings = false` switches the JS sourcemap upload off.
`bugsnag.enabled = false` switches the whole plugin off, including source map uploading.

> do I also need to set enabled if I'm using variant filters?

I'd recommend that you do set `enabled` to `false` for variants that you don't want Bugsnag to run on, just so that you don't have any assets uploading needlessly.

**Comment by xander-jones** [comment]
@cristianoccazinsp, a little follow-up on this! There's a great [reference document here](https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html) for the `ACTION` and `DEPLOYMENT_LOCATION` variables. 

```
ACTION
```

Identifies the type of build to perform on the target.

- `build`: Build the product and place it in the product build directory (`CONFIGURATION_BUILD_DIR`).
- `clean`: Remove the product and build files in the product build directory (`CONFIGURATION_BUILD_DIR`) and the intermediate build files directory (`CONFIGURATION_TEMP_DIR`).
- `install`: Build the product and place it in its installation destination (`INSTALL_PATH`).
- `installhdrs`: Copy the product’s public and private header files into the public headers directory (`PUBLIC_HEADERS_FOLDER_PATH`) and the private headers directory (`PRIVATE_HEADERS_FOLDER_PATH`), respectively.
- `installsrc`: Copy the target’s source files into the project directory (`SRCROOT`).

```
DEPLOYMENT_LOCATION
```

Boolean value. Specifies whether product files are placed in the installation (specified by `DSTROOT`) or the build directory (identified by `SYMROOT`).

- `YES`: Product files are placed in `$DSTROOT`.
- `NO`: Product files are placed in `$SYMROOT`.

**Comment by cristianoccazinsp** [comment]
It says it is a "retired document", but I guess the info is still valid.  Anyways, with your first response I believe I got it to work as expected now.  Thanks!

**Comment by mattdyoung** [comment]
Closing this as the above advice should allow users of the CLI to configure the uploads to only happen on builds where they do require the source maps to be uploaded.
