### ISSUE TITLE
[React Native] Support Hermes for IOS

### ISSUE THREAD

**Issue by smacgregor** [bugsnag/bugsnag-js#1358]
### Description
React Native 0.64 adds support for [Hermes on IOS](https://reactnative.dev/blog/2021/03/12/version-0.64). 

**Describe the solution you'd like**
Please support Hermes on IOS.

**Comment by xander-jones** [comment]
👋 hey @smacgregor, this is something that we'll be taking a look into. We'll let you know as soon as Bugsnag support for Hermes on iOS is available.

**Comment by bliang** [comment]
Yeah we would like to see this in as well to get the performance gains of Hermes!

**Comment by alexkuttig** [comment]
@xander-jones is there any progress on this? We'll release our app on monday and would love to have the sourcemaps for hermes in there.

**Comment by mattdyoung** [comment]
Hi! We're still at the stage of designing the required changes for Hermes source maps on iOS so we don't have a timeline for release yet, but this is being worked on. We'll provide updates here as soon as we release support for this.

**Comment by johnkiely1** [comment]
We now support Hermes on iOS. You can find our updated documentation here:
https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#ios

**Comment by pedpess** [comment]
Hi @mattdyoung and @xander-jones, before I update my project to use Hermes for iOS. Does your library still sends the Hermes source maps like used to be automatically, or do I need to get back to the manual way of uploading it to Bugsnag?

**Comment by xander-jones** [comment]
Hey @pedpess, unfortunately because source map output works a little differently when using Hermes (for both Android and iOS), you won't be able to use the Bugsnag automatic source map uploads.

However, that's not to say that you can't automate it in your pipeline post-build: You can find our docs on how to get & upload source maps here: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#hermes

**Comment by xander-jones** [comment]
@pedpess 🤦 apologies, an error in my previous comment that has now been updated: yes, you can use automated source map uploads with Hermes on iOS and Android (so long as you're not also using CodePush: in which case check out the docs here: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#codepush-and-hermes

**Comment by pedpess** [comment]
Thanks, @xander-jones 🙏🏻 . In my case, I'm not using CodePush to make JS releases. So, I can expect that my Bugsnag Fastlane plugin on iOS 🍎 and the Gradle Bugsnag plugin on Android 🤖 will do the job for me?

**Comment by taylorkline** [comment]
> if you are already automatically uploading source maps to Bugsnag using the automated method as described [here](https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#source-maps), no changes are required. Once you flip the switch to enable Hermes, clean, and build your new project, we'll automatically pick up source maps and upload them!
> 
> If you've _never_ enabled Bugsnag automatic source maps upload before, you can enable this by just running `npx @bugsnag/react-native-cli automate-symbolication`. This injects code in two places to your project to enable auto source map uploads:
> 
> * in Android: it just adds a Gradle flag to enable uploads!
> * in iOS: it's injecting code into the Xcode project itself. It adds to the `Bundle React Native code and images` build phase an extra flag, then adds a _new_ build phase that calls out to a script to complete the upload.
> 
> You can review all of the change the command above makes with your source control tool.

@xljones Just to confirm, has this behavior been gutted from the CLI? The `automate-symbolication` command now seems to just add some `package.json` scripts and automating it is now "DIY," and even the Bugsnag React Native documentation now just unhelpfully states,

> For a fully automated upload process, you can integrate these calls into a native Gradle task and Xcode post-build phase, or equivalent for your build system.

**Comment by hannah-smartbear** [comment]
Hi @taylorkline,

Yes, we can confirm that the full automation of uploads has been removed from the CLI due to fundamental changes in the build system of React Native 0.71. Given the variety of ways developers setup their builds, we decided to favor [providing a set of tools to perform the uploads](https://docs.bugsnag.com/platforms/react-native/react-native/showing-full-stacktraces/#bugsnag-react-native-cli-init) and leave the automation part to developers to add to their build and release processes as they see fit. It should be as simple as calling `npm run bugsnag:upload` to upload all types at once, or it can be broken down into separate commands (e.g. `npm run bugsnag:upload-rn-android`) to do individual file types. You can also [integrate against the CLI directly](https://docs.bugsnag.com/build-integrations/bugsnag-cli/#react-native-symbols) to cut out npm altogether if that suits.
