### ISSUE TITLE
[Android] Upload to Bugsnag command being triggered before JS sourcemaps are built

### ISSUE THREAD

**Issue by pedpess** [bugsnag/bugsnag-js#1381]
Hi Bugsnag team,

I wrote you an e-mail last Friday but thought about also having this discussion here as it may help others figure it out as well. Hope it's okay :)

Currently in my Android setup **with Hermes enabled**, after using the automated workflow of uploading the sourcemaps to Bugsnag with:

`build.gradle`
```
bugsnag {
  uploadReactNativeMappings = true
}
```

I noticed that the Bugsnag Gradle task that uploads the JS sourcemaps is skipping cos the JS sourcemaps doesn't exist yet with this message:
```
Bugsnag: JS sourcemaps and JVM/NDK mapping files are not uploaded when using the react-native CLI (e.g. react-native run-android --variant=release). You should generate a release APK using ./gradlew assembleRelease or ./gradlew bundleRelease instead. See the React Native docs for further info: https://reactnative.dev/docs/signed-apk-android#generating-the-release-apk
```

In my Gradle task tree in Android Studio, Bugsnag Gradle is running before React Gradle, which is the task that should generate the JS sourcemaps, so that's why I think it skips, not sending the JS sourcemaps of Android to Bugsnag's website.

Do you know how I could change the order of my Gradle tasks so Bugsnag Gradle could run just after the JS sourcemaps exist?

**Comment by johnkiely1** [comment]
Hey @pedpess, 

As you are obviously aware we have discussed this further via the email chain and came to the conclusion that `codeBundleId` would need to be removed in order to get correct upload behaviour. 

For future travellers:

`codeBundleId` is generally reserved for CodePush based apps (as they need a different identifier compared to the application binary version):
If you are using CodePush, or wish to continue using codeBundleId for any other reason, you will need to manually upload your maps using the @bugsnag/source-maps CLI tool, ensuring that you add the `--code-bundle-id` option: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#codepush

If you are not using CodePush, I would suggest dropping `codeBundleId` completely, instead ensuring that your app.version and app.versionCode match the sourcemaps which you are uploading.

If using Hermes on its own the following instructions would apply for how to generate and upload the source maps. https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#hermes

I'll go ahead and close this ticket but do let me know if you have any more issues.
