### ISSUE TITLE
Add ability to update config after start()

### ISSUE THREAD

**Issue by swrobel** [bugsnag/bugsnag-js#1395]
### Description
Some config values, such as `codeBundleId` should be able to be modified at runtime.

**Describe the solution you'd like**
```js
const localPackage = await CodePush.getUpdateMetadata()
if (localPackage) {
  Bugsnag.updateConfig({
	codeBundleId: localPackage.label
  })
}
```

See the CodePush docs for [more examples](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#codepushgetupdatemetadata)

**Describe alternatives you've considered**
Hardcoding the codepush version, but that's error-prone. I would rather just get it dynamically from the source.

**Comment by xander-jones** [comment]
Hey @swrobel, `codeBundleId` is not modifiable after initialization by design, as it should be set during initialization of Bugsnag. The reason for this is so that errors that occur in your application will contain the `codeBundleId` value, _regardless_ of how early the error happens in your application's lifecycle.

The `getUpdateMetadata()` method runs asynchronously, and so the `label` value which would get used to apply to the `codeBundleId` won't be available as soon as the application starts. This in turn means you'll either:

* need to wait for the `Promise` to complete, delaying the initialization of Bugsnag until you've got the `label` value risking missing crashes and errors early in your app before Bugsnag is started, or
* errors early in your application, before `codeBundleId` is set (if you were able to update the `codeBundleId` value after initialization), wouldn't be mappable by your source maps as there wouldn't be a `codeBundleId` to match on.

FWIW: I can understand the rationale behind what you're looking to do as this would automate the setting of the `codeBundleId`, but the trade-off of not receiving or mapping errors that occur early in your application mapped is pretty severe.

One suggestion that may work for you here though; when performing a CodePush update, the labelling scheme is consistent, the integer part of the [`label` string](https://docs.microsoft.com/en-us/appcenter/distribution/codepush/rn-api-ref#properties) will increment by one each time an update is made, so you could:

* `grep` the `appcenter` CLI to get the current label.
* increment the integer component value by one, and inject it into your source `codeBundleId` value (e.g. codeBundleId could read from your `package.json`, and you put the incremented label into that file)
* run your CodePush update
* upload your source maps to Bugsnag using the `codeBundleId` that you generated earlier.

With this method; you can start Bugsnag immediately at the start of your app without any dependency on asynchronous calls, and there's no risk of the CodePush `codeBundleId` being set too late.

**Comment by swrobel** [comment]
Wow, what a response... While I appreciate the fact that you think it's severe that early errors wouldn't be properly mapped, I think that's a tradeoff I'm willing to make to avoid improperly mapping them due to human error. FWIW, I already hacked a workaround:

```js
NativeModules.BugsnagReactNative.updateCodeBundleId(localPackage.label)
```

**Comment by mattdyoung** [comment]
Hi @swrobel 

It's also worth noting that the `codeBundleId` is just intended to be a unique version identifier which you change each time you update your JS bundle. It doesn't need to map to the CodePush label.

We don't intend to change the interface to make the `codeBundleId` config modifiable after initialization for the reasons Xander mentioned around the risk of errors being reported before it is set.

If you really wanted to set it dynamically after initialization this can be overridden as `event.app.codeBundleId` in an `onError` callback on Android and iOS:
https://docs.bugsnag.com/platforms/android/customizing-error-reports/#app
https://docs.bugsnag.com/platforms/ios/customizing-error-reports/#app

Thanks!

**Comment by swrobel** [comment]
Thanks @mattdyoung - I did a pretty thorough search of the docs before posting this and I'm realizing the reason I didn't realize I could add it as an `onError` callback is that it doesn't come up in the Algolia docs search:
<img width="489" alt="Screen Shot 2021-05-19 at 12 27 40 PM" src="https://user-images.githubusercontent.com/157270/118872847-e23da880-b89d-11eb-953e-46d01bdcb471.png">

**Comment by mattdyoung** [comment]
@swrobel - thanks for mentioning that regarding the Algolia search. I'll feed that back to the team and see if there's a way for us to improve the search results.
