### ISSUE TITLE
React-Native [bugsnag] Cannot set "maxBreadcrumbs" configuration option in JS. This must be set in the native layer.

### ISSUE THREAD

**Issue by idanlevi1** [bugsnag/bugsnag-js#1409]
I used Bugsnag with React Native,
I try to set maxBreadcrumbs to 100 for example and I get a warning:
`React-Native [bugsnag] Cannot set "maxBreadcrumbs" configuration option in JS. This must be set in the native layer.` 

my code: 

```
 Bugsnag.start({
    maxBreadcrumbs: 40
  })
```

Versions: 

> react-native: 0.61.5

> @bugsnag/react-native: 7.9.5

**Comment by xander-jones** [comment]
Hey @idanlevi1 👋 , that's expected behaviour. The maximum breadcrumb value is set in the native layer, not on the JavaScript side: https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#maxbreadcrumbs

Here's how it's done:
* on Android: https://docs.bugsnag.com/platforms/android/configuration-options/#maxbreadcrumbs, and
* for iOS: https://docs.bugsnag.com/platforms/ios/configuration-options/#maxbreadcrumbs
