### ISSUE TITLE
 SOURCE_MAP was not specified, falling back to [path]; on upload via ios PhaseScript

### ISSUE THREAD

**Issue by Gerlison** [bugsnag/bugsnag-js#1473]
### Describe the bug
After updating @bugsnag/react-native to the 7.10.5 version from 7.6.x, my upload PhaseScript broke.

`Ensure the --sourcemap-output option is passed to the react-native bundle command. - Command PhaseScriptExecution failed with a nonzero exit code`

But when I checked on the CHANGELOG it mentioned nothing about the change on scripts. So I searched on the docs and there it was, a brand new path for the script. So I changed and it worked.

SO PLEASE, update your CHANGELOGS with that information.

### Steps to reproduce
1. Update to lastest version
2. Try to build a release on xcode

### Environment
* Bugsnag version: 7.10.5
* React Native
* Device (e.g. iphonex): iPhone 8

**Comment by xander-jones** [comment]
Hey @Gerlison, thanks for raising. We'll take a look into correcting for this.

**Comment by xander-jones** [comment]
👋. This change was made to support source bundle/map filenames which had spaces in them (https://github.com/bugsnag/bugsnag-js/pull/1289)  by sending them to a guaranteed non-whitespace directory and filename, and then sending that filename into the script to perform the upload.

However, if this option is missing you'll see the message as above where we fallback to using the original `$BUNDLE_FILE.map` which is located at: `$CONFIGURATION_BUILD_DIR/$UNLOCALIZED_RESOURCES_FOLDER_PATH/main.jsbundle.map` where the original file should be. Because this change has a fallback, it was not documented as a breaking change.

For clarity, I've added these details for future travellers into a changelog entry that was indeed missing.

**Comment by Gerlison** [comment]
Thank you for the support and understanding, I appreciate it. S2
