### ISSUE TITLE
Bugsnag native service status for JS part of application [React Native]

### ISSUE THREAD

**Issue by runewizard** [bugsnag/bugsnag-js#1525]
### Description

After upgrade from the [old deprecated version](https://github.com/bugsnag/bugsnag-react-native) to the new one, we faced an issue when our app crashed on the splash screen without reasonable error.
Unfortunately, we weren't able fast to figure out what was the reason for those crashes. We found that we have an issue with our CI and in this particular case Bugsnag API key was not provided. 
We also have a check for preventing service start with an empty key from the native side:
```
if(BuildConfig.BUGSNAG_API_KEY != null && !BuildConfig.BUGSNAG_API_KEY.isEmpty()) {
   Bugsnag.start(this);
}
```
In our case key was empty and the native service didn't start. But with [the current implementation](https://github.com/bugsnag/bugsnag-js/tree/next/packages/react-native) JS part of Bugsnag service basically doesn’t know about the state of native service. And calling `Bugsnag.start` crashed the app on the splash screen.

It will be great to have from JS part method or the flag to verify the current status of native service for preventing such kind of errors.
Another possible option is suppressing error in the described case https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/src/config.js#L93.

Thanks in advance

**Comment by luke-belton** [comment]
Hi @runewizard - just to check I am understanding you correctly. When the Bugsnag API key isn't properly configured, your app is crashing as a result of the error on this [line](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/src/config.js#L93). In cases where the API key is not configured in the native layer, you would prefer to see that `Bugsnag.start` from the JS layer does not cause a crash in your app?

**Comment by runewizard** [comment]
Hey @luke-belton!
We didn't even run native service unless the API key has been provided.
In the case where `native service is not running`, it would be nice to have no failures when calling the JS layer. Or, alternatively, Bugsnag could provide an API to check the state of the native service from the JS layer.

**Comment by luke-belton** [comment]
Thanks! In that case, for your current setup we'd recommend conditionally starting your JS layer in the same way as your native layer based on availability of the API key in the current build environment. It is by design that the JS layer throws an error if the native layer is not running.

You could also consider using the [`enabledReleaseStages`](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#enabledreleasestages) config option if you want to conditionally start Bugsnag based on your environment - this ensures that your app better emulates your production environment across all release stages. I would also reassure you that the Bugsnag API key can only be used to send error reports/source maps to Bugsnag so you could consider storing it directly in your Build Config, rather than (presumably) injecting it through your CI (see discussion e.g. at https://github.com/bugsnag/bugsnag-js/issues/595#issuecomment-514578712).
