### ISSUE TITLE
[React Native] Allow adding releaseStage in JS?

### ISSUE THREAD

**Issue by kyle-ssg** [bugsnag/bugsnag-js#1575]
### Description
I'm using codepush in a single app with production and staging deployments, from what I can see there is no way to specify the release stage as development for the Staging codepush releases.

**Describe the solution you'd like**
I'd like to be able to specify the release stage when calling Bugsnag.start

```
  const {codeBundleId,releaseStage} = require("../app.json");

  Bugsnag.start({
    codeBundleId,
    releaseStage
```

**Describe alternatives you've considered**
I don't really see any alternative since we manage releases via CodePush inside a single native app.

**Comment by xander-jones** [comment]
Hey @kyle-ssg, it's expected that the JS bundle and native application release stages should match, which is why a release stage is not separately configurable for native and bundle.

In this scenario, you'd end up with a `staging` bundle deployed on a `production` binary. This sounds a bit risky as your users would be downloading a staging/development build to their production applications.

However, one alternative you can consider is to override the release stage for JavaScript errors if the `releaseStage` in `../app.json` is found to not match that in the binary: 

```js
const {codeBundleId, releaseStage} = require("../app.json");

Bugsnag.start({
  onError: function (event) {
    if (releaseStage !== event.app.releaseStage) {
      event.app.releaseStage = releaseStage;
    }
  },
  codeBundleId
});
```

A couple of side-notes: 
* I'm not sure how you'd end up pushing a staging release to a production bundle in any case as the CodePush deployment key would need to change on the binary if you're using a seperate CodePush staging lane, which by extension, the release stage could be changed at the same time in the native binary.
* Please note that the alternative above would report JS errors from the release stage as defined in `../app.json`, but native errors from the release stage as defined in the binary; which is correct, but might be a bit confusing.

**Comment by xander-jones** [comment]
Hey @kyle-ssg, hopefully the example in the message above helps you resolve this, so closing out this issue but let us know if this is still a problem 😊
