### ISSUE TITLE
[@bugsnag/plugin-react] Peer dependency of @bugsnag/core not needed

### ISSUE THREAD

**Issue by amhunt** [bugsnag/bugsnag-js#1582]
### Describe the bug
We receive a warning about missing `@bugsnag/core`, since it's listed as a peer dep for `@bugsnag/plugin-react`. According to the docs, we only need `@bugsnag/js`, so I believe the `@bugsnag/core` dep should be moved to `optional` dependencies?

yarn warning: ` @bugsnag/plugin-react@7.13.2" has unmet peer dependency "@bugsnag/core@^7.0.0".`

### Steps to reproduce
run `yarn` or `npm install` in a project without `@bugsnag/core` installed

### Environment
* Bugsnag version: ^7.13.2 (js and plugin-react)
* Browser framework version (if any):
    * React: 16.14
* Browser version (e.g. chrome, safari): N/A
* Device (e.g. iphonex): N/A

### Example code snippet 

```
yarn
```

<details><summary>
yarn warning: ` @bugsnag/plugin-react@7.13.2" has unmet peer dependency "@bugsnag/core@^7.0.0".`
</summary>

```

```
</details>

**Comment by yousif-bugsnag** [comment]
Hi @amhunt,

This is something we're aware of and is an issue with yarn specifically - the unmet peer dependency warning is down to yarn not behaving well, in our opinion. It happens because technically there's nothing requiring `@bugsnag/core` to be available to `@bugnsag/plugin-react`. Yarn _could_ put `@bugsnag/core` only in the packages that have a hard dependency on it (i.e. `@bugsnag/browser`) which would then make it inaccessible to `@bugsnag/plugin-react`.

However doing that wouldn’t make sense and would break so many packages that they can’t really change that behaviour, so it should always be accessible.

We used to use real dependencies for `@bugsnag/core`, but this meant each plugin could end up with its own copy with different versions. That’s bad for a few reasons, but a big one is that the typescript types can cause apps to stop compiling if you mix two versions. Peer dependencies solve that problem, but also bring their own issues such as this.

The `@bugsnag/core` package does get installed, despite the warning from yarn, so there shouldn't be any real issue with the plugin. You can check this by running `yarn list`. If you would like to suppress these warnings you can require the package explicitly using yarn add `@bugsnag/core`.

**Comment by amhunt** [comment]
@yousif-bugsnag makes sense! Thanks for the thorough response. I didn't realize @bugsnag/core was truly required, and was being installed anyway. We will add it to our dependency list explicitly.
