### ISSUE TITLE
BSG_KSBacktrace_Private.h file not found in XCode 13.1

### ISSUE THREAD

**Issue by roysailor** [bugsnag/bugsnag-js#1583]
### Describe the bug

The build for iOS is failing with the following error: 'BSG_KSBacktrace_Private.h' file not found

### Environment
* Bugsnag version: "@bugsnag/react-native": "^7.11.0"
* Browser framework version (if any):
    * React Native: 0.63.4
* Device (e.g. iphonex): iPhone 11 (14.2)
* XCode Version: 13.1

**Comment by yousif-bugsnag** [comment]
Hi @roysailor, 

We haven't been able to reproduce the issue you're seeing when building a React Native project with Bugsnag integrated on XCode 13.1. Are you able to provide a cut down reproduction example? Or alternatively please can you write in to support@bugsnag.com with details of how you have configured Bugsnag so that we can investigate further?
