### ISSUE TITLE
Add a method to destroy the Bugsnag client

### ISSUE THREAD

**Issue by raygesualdo** [bugsnag/bugsnag-js#1604]
### Description

In our application, we create the Bugsnag client as the very first step in our JavaScript bundle. Later in our application's bootstrapping process, we check to see if the user is in the EU and have to hack Bugsnag to disable it (see Alternative section). Our current solution depends on `Client` private internals and will probably be prone to breakage as we keep up with the latest Bugsnag version.

**Describe the solution you'd like**

Ideally, there would be a single method (e.g. `.destroy`, `.teardown`, `.disable`) that disables the client entirely and no longer sends events to Bugsnag's servers.

**Describe alternatives you've considered**

Currently, we are having to swap out the instantiated client's delivery methods for noop functions:

```js
const NOOP = () => {}
const stub = { sendSession: NOOP, sendEvent: NOOP }
client._setDelivery(() => stub)
```

**Comment by yousif-bugsnag** [comment]
Hey @raygesualdo, rather than overriding the client's internal delivery methods, have you considered using the public `onError` and `onSession` callbacks? Returning `false` from these will prevent errors and sessions from being sent to Bugsnag, so these can be used to conditionally enable/disable Bugsnag's reporting in much the same way:
https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#discarding-events 
https://docs.bugsnag.com/platforms/javascript/capturing-sessions/#discarding-and-amending-sessions

**Comment by raygesualdo** [comment]
Ahh, that's a good suggestion. Let me give that a shot. That should solve our use case. Is there any other data the client sends to the Bugsnag servers that wouldn't be covered by those callbacks? For instance, does `.setUser` send a network request?

**Comment by yousif-bugsnag** [comment]
No, the only data Bugsnag sends is in the form of event and session payloads, which would be covered by those callbacks. Methods such as `setUser` simply set metadata values to be included in those payloads, so this should be all that's needed to disable the JS client.

One important caveat to note is that for React Native projects any callbacks set in JavaScript will only be triggered for JavaScript errors, so for RN this should be done using native callbacks as they will be run for all errors and after any JavaScript callbacks have completed.
