### ISSUE TITLE
Using uploadReactNativeMappings = true, and having enableHermes=true gives "A source map was found but could not be applied because it doesn't match the code."

### ISSUE THREAD

**Issue by yberstad** [bugsnag/bugsnag-js#1609]
### Describe the bug
I have used `npx @bugsnag/react-native-cli automate-symbolication` to set the uploading of react native source mapping.  

But when I also set enableHermes=true I get :
`A source map was found but could not be applied because it doesn't match the code.`. 

If I set enableHermes=false, and do a rebuild, everything works fine and I do not get a warning in the Bugsnag UI.

I see that the source map is uploaded in both cases going into Project settings > Source maps

### Environment
    @bugsnag/react-native: ^7.14.0,
    @bugsnag/source-maps: ^2.3.0,
    react-native: 0.66.3,

I only get this issue on Android.

With Hermes enabled:
![Screenshot 2021-12-07 at 12 18 57](https://user-images.githubusercontent.com/2823722/145020272-37fbeabe-7542-48f2-b3ce-d0b9398f8d33.png)

Without Hemes enabled:
![Screenshot 2021-12-07 at 12 22 39](https://user-images.githubusercontent.com/2823722/145020491-68ca3748-9ecf-4c51-99dc-59b850de916b.png)

I have dug into the react-native/react-gradle, and I see that `sourcemap-output`  varies depending on whether hermes is enabled or not.

```
            commandLine(*execCommand, bundleCommand, "--platform", "android", "--dev", "${devEnabled}",
                "--reset-cache", "--entry-file", entryFile, "--bundle-output", jsBundleFile, "--assets-dest", resourcesDir,
                "--sourcemap-output", enableHermes ? jsPackagerSourceMapFile : jsOutputSourceMapFile, *extraArgs)
```

Logging the values:
```
jsPackagerSourceMapFile: android/app/build/intermediates/sourcemaps/react/bntest/release/index.android.bundle.packager.map
jsOutputSourceMapFile: android/app/build/generated/sourcemaps/react/bntest/release/index.android.bundle.map
```

Do the uploadReactNativeMappings take sourcemap-output variations depending on if hermes is enabled or not, into account?

Any help is appreciated, thanks in advance!

**Comment by xander-jones** [comment]
Hey @yberstad are you cleaning the project between builds? I'm wondering if there are some leftovers from the non-Hermes build interfering. Use `cd android && ./gradlew clean`: https://reactnative.dev/docs/hermes#android

> Do the uploadReactNativeMappings take sourcemap-output variations depending on if hermes is enabled or not, into account?

Yes, we [build the path to the sourcemap](https://github.com/bugsnag/bugsnag-android-gradle-plugin/blob/v7.1.0/src/main/kotlin/com/bugsnag/android/gradle/BugsnagUploadJsSourceMapTask.kt#L176-L189), as RN's Gradle script can modify the output source map path: https://github.com/facebook/react-native/blob/v0.66.3/react.gradle#L175

**Comment by yberstad** [comment]
Hi @xander-jones, thank you for your quick reply! 

Yes I'm cleaning the project between builds. I now deleted the whole build folder, but I still get the error.

From the output of the build.

With hermes:
```
Bugsnag: uploading react native sourcemap: [/Users/oyvind/myagent/_work/1/s/node_modules/@bugsnag/source-maps/bin/cli, upload-react-native, --api-key, <our-api-key>, --app-version, 4.0.0, --app-version-code, 514, --platform, android, --source-map, /Users/oyvind/myagent/_work/1/s/android/app/build/generated/sourcemaps/react/prodtest/release/index.android.bundle.map, --bundle, /Users/oyvind/myagent/_work/1/s/android/app/build/intermediates/bugsnag/rescued/Prodtest-release.android.bundle, --project-root, /Users/oyvind/myagent/_work/1/s]
Bugsnag: uploaded react native sourcemap: [info] Preparing upload of React Native source map (release / android)
[debug] Reading source map "/Users/oyvind/myagent/_work/1/s/android/app/build/generated/sourcemaps/react/prodtest/release/index.android.bundle.map"
[debug] Reading bundle file "/Users/oyvind/myagent/_work/1/s/android/app/build/intermediates/bugsnag/rescued/Prodtest-release.android.bundle"
[info] Applying transformations to source map
[debug] Ensuring sourcesContent field is populated
[debug] Stripping project root from sources
[debug] Initiating upload to "https://upload.bugsnag.com/react-native-source-map"
[success] Success, uploaded /Users/oyvind/myagent/_work/1/s/android/app/build/generated/sourcemaps/react/prodtest/release/index.android.bundle.map and /Users/oyvind/myagent/_work/1/s/android/app/build/intermediates/bugsnag/rescued/Prodtest-release.android.bundle to https://upload.bugsnag.com/react-native-source-map in 2030ms
```

Without hermes:
```
Bugsnag: uploading react native sourcemap: [/Users/oyvind/myagent/_work/1/s/node_modules/@bugsnag/source-maps/bin/cli, upload-react-native, --api-key, <our-api-key>, --app-version, 4.0.0, --app-version-code, 515, --platform, android, --source-map, /Users/oyvind/myagent/_work/1/s/android/app/build/generated/sourcemaps/react/prodtest/release/index.android.bundle.map, --bundle, /Users/oyvind/myagent/_work/1/s/android/app/build/generated/assets/react/prodtest/release/index.android.bundle, --project-root, /Users/oyvind/myagent/_work/1/s]
Bugsnag: uploaded react native sourcemap: [info] Preparing upload of React Native source map (release / android)
[debug] Reading source map "/Users/oyvind/myagent/_work/1/s/android/app/build/generated/sourcemaps/react/prodtest/release/index.android.bundle.map"
[debug] Reading bundle file "/Users/oyvind/myagent/_work/1/s/android/app/build/generated/assets/react/prodtest/release/index.android.bundle"
[info] Applying transformations to source map
[debug] Ensuring sourcesContent field is populated
[debug] Stripping project root from sources
[debug] Initiating upload to "https://upload.bugsnag.com/react-native-source-map"
[success] Success, uploaded /Users/oyvind/myagent/_work/1/s/android/app/build/generated/sourcemaps/react/prodtest/release/index.android.bundle.map and /Users/oyvind/myagent/_work/1/s/android/app/build/generated/assets/react/prodtest/release/index.android.bundle to https://upload.bugsnag.com/react-native-source-map in 1853ms
```


To me it seems like the source map is the same even if we are using hermes or not? 

And what is the `/bugsnag/rescued/Prodtest-release.android.bundle ` that is used while using hermes?

**Comment by yousif-bugsnag** [comment]
Hi @yberstad,

> what is the /bugsnag/rescued/Prodtest-release.android.bundle that is used while using hermes?

This is generated by us - Hermes overwrites the generated JS bundle, so we save the unmodified bundle before that happens.

Can you send us a link to an example event in your Bugsnag Dashboard that is displaying the 'source mapping failed' banner so that we can investigate further? You can write in to us at support@bugsnag.com or drop a link here.

**Comment by yberstad** [comment]
@yousif-bugsnag, thanks for getting back to me! I sendt you an mail with the info you requested.

**Comment by yousif-bugsnag** [comment]
Hi @yberstad, thanks for getting in touch! Your link helped us to pin down what was happening here. The issue has now been resolved via the support ticket, but for the benefit of future travellers:

When using Hermes, the bundling works as follows:

- Metro builds a JS bundle with a source map.
- Hermes compiles the JS bundle to bytecode and creates its own (partial) source map.
- The source maps from (1) and (2) are merged to create the final source map (see [here](https://github.com/facebook/react-native/blob/3b5e4463ae5662743a6ee1ac6251db52d7af78f2/react.gradle#L216))

The final combined source map is what is uploaded to Bugsnag - this contains the correct mappings to be able to map back from the hermes bytecode bundle to the original JS sources.

The reason the 'source mapping failed' banner is being shown in this particular case is that the event stacktrace contains frames originating from hermes internal bytecode, e.g. `/tmp/hermes/.../InternalByteCode.js`. 

Since this is not part of the app bundle the source map does not contain mappings for those frames, leading to the warning banner being displayed, but the source map is valid and all other frames are being mapped correctly. 

We have an item on our roadmap to make that banner clearer in situations such as this where we are able to apply source maps to some frames and not others.
