### ISSUE TITLE
Support CodePush with auto-adding sourcemaps

### ISSUE THREAD

**Issue by henrymoulton** [bugsnag/bugsnag-js#1615]
### Description

If I remember correctly while running the setup script of Bugsnag, it adds this Build Phase:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/30093692/145318225-a3437157-838f-4bad-bd2b-a017324dfcb0.png">

which runs a script `bugsnag-react-native-xcode.sh` with these args:

```
ARGS=(
    "--api-key" "$API_KEY"
    "--app-bundle-version" "$BUNDLE_VERSION"
    "--app-version" "$APP_VERSION"
    "--bundle" "$BUNDLE_FILE"
    "--platform" "ios"
    "--source-map" "$SOURCE_MAP"
    "--project-root" "$PROJECT_ROOT"
    )
```

However if I'm using CodePush (regardless of it being a native release), Bugsnag expects a code bundle ID, which the args above is not providing:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/30093692/145318326-22cefbf0-e51c-441a-8c36-8147827cff43.png">

**Describe the solution you'd like**

Have I got this right that the script should use `--code-bundle-id` instead in this case?

```
ARGS=(
    "--api-key" "$API_KEY"
    "--code-bundle-id" "$APP_VERSION-$BUNDLE_VERSION"
    "--bundle" "$BUNDLE_FILE"
    "--platform" "ios"
    "--source-map" "$SOURCE_MAP"
    "--project-root" "$PROJECT_ROOT"
    )
```

I'd love to understand this a bit more!

**Comment by yousif-bugsnag** [comment]
Hi @henrymoulton,

Thanks for the suggestion! Unfortunately automatic source map uploads from xcode isn't something we can support reliably for CodePush, since JS bundles and source maps can be generated without performing a binary build, and the CodePush label is not known at binary build time. 

If you're using CodePush you will therefore need to upload source maps manually using the `@bugsnag/source-maps` CLI: https://docs.bugsnag.com/build-integrations/js/source-maps-react-native/#codepush

**Comment by henrymoulton** [comment]
> Unfortunately automatic source map uploads from xcode isn't something we can support reliably for CodePush..  and the CodePush label is not known at binary build time.

Actually as long as it follows a specific format (and on several apps I've worked on, it always has), the codeBundleId for native builds would be ${VERSION}-${BUILD_NUMBER}.

**Comment by henrymoulton** [comment]
I think my specific question is, since I've not seen it documented anywhere:

From the moment I start using `codeBundleId` to upload Sourcemaps, do I need to use that for ALL sourcemap uploads (including native builds)?

**Comment by xander-jones** [comment]
Hey @henrymoulton, yes you can add `--code-bundle-id` to the run script without issue as this just means it'll match against the JS bundle uploaded at build time of the binary - no worries there! You'll just want to make sure the variables are populated as you'd expect on the input to this argument.

What @yousif-bugsnag was noting is that we wouldn't support code bundle ID directly through Xcode by default because it just is not required for a binary build, which does lead in to your follow up question...

> From the moment I start using codeBundleId to upload Sourcemaps, do I need to use that for ALL sourcemap uploads (including native builds)?

No, you do not need to always use `codeBundleId` once it's used once. You can use a mix. Take for example, you're setting out building your first version of your app, and you create release `A`: appVersion 1.0.0, bundleVersion 100. Then, you create two CodePush releases for this binary: `B`, and `C`, in which you now set a `codeBundleId` of `v2`, and `v2`. 

Your source map uploads should look like this:

| Release | appVersion | bundleVersion | codeBundleId |
|---------|------------|---------------|--------------|
| A       | 1.0.0      | 100           | -            |
| B       | 1.0.0      | 100           | v2     |
| C       | 1.0.0      | 100           | v3     |

A report from release `A`, `B`, or `C` will match the respective source map above. But it is important that the`codeBundleId` reported in release `A` is `null`.

Alternatively, you can just use `codeBundleId` even in your original binary release (`D`) (with your modification to the run script above) as follows (I think this is how you've described your release version pattern), then your CodePush updates would just bump the `codeBundleId` along in released `E`, and `F`. In this case the appVersion and bundleVersion are just filler, they're not using for map matching at all.

| Release | appVersion | bundleVersion | codeBundleId |
|---------|------------|---------------|--------------|
| D       | 1.0.0      | 100           | 1.0.0-v1     |
| E       | 1.0.0      | 100           | 1.0.0-v2     |
| F       | 1.0.0      | 100           | 1.0.0-v3     |
