### ISSUE TITLE
Electron application generates error with @bugsnag/electron

### ISSUE THREAD

**Issue by andres-mestra** [bugsnag/bugsnag-js#1628]
### Describe the bug
Error after compiling the electron application and running in windows 10, it does not load due to the error

![](https://res.cloudinary.com/dp7wliirv/image/upload/v1640365441/error_m532rd.png)

### Steps to reproduce
1. create electron application with electron-forge
    https://www.electronforge.io/guides/framework-integration/react-with-typescript
2. integrate ReactJs
  https://www.electronforge.io/guides/framework-integration/react-with-typescript
3. install bugsnag
   https://docs.bugsnag.com/platforms/electron/
4. make app and execute .exe

### Environment
* Bugsnag version:
   * @bugsnag/electron: 7.14.1
* Browser framework version:
    * React: 17.0.2
* Electron version: 16.0.5
    * @electron-forge/cli: 6.0.0-beta.61

* Browser version: 
   * Chromedriver: 96.0.0
* Windows: 10

### Example Repo 
   https://github.com/andres-mestra/error-bugsnag-electron

## Possible error

In line 21 of the main process configuration of the @bugsnag/electron package, the argument 'userCache' is not valid for 
```js
electron.app.getPath ('userCache')
```
https://github.com/bugsnag/bugsnag-js/blob/next/packages/electron/src/client/main.js
Change argument for: 

```js
electron.app.getPath ('cache')
```
See Electron documentatión:
https://www.electronjs.org/docs/latest/api/app#appgetpathname

**Comment by mattdyoung** [comment]
The use of `userCache` is right, although that isn't clear from the electron documentation:
https://github.com/electron/electron/blob/4600d7e7f659092e31ca125f2a871067802ac14f/shell/browser/api/electron_api_app.cc#L482-L483

I've done some testing with your reproduction case and believe the exception is happening due to the API key not being set, which triggers an exception [here](https://github.com/bugsnag/bugsnag-js/blob/66846c5a5e449365227b9d2d88a59339f0499cff/packages/electron-filestore/filestore.js#L10). You have:
```
Bugsnag.start({
  apiKey: process.env.BUGSNAG,
});
```

I was initially able to reproduce the same error when running the built app, but then setting the `BUGSNAG` environment variable to a valid value resolved the issue. Can you confirm whether setting a valid API key resolves the issue for you?

The exception raised is admittedly unhelpful so we're planning to look at improving the API key validation to make this clearer.

**Comment by andres-mestra** [comment]
Hello
The bug was assuming that process.env.BUGSNAG returns a string but it doesn't.

Solution: 
```js
Bugsnag.start({
  apiKey: `${process.env.BUGSNAG}`,
});
```
It must be validated because it works when the `electron-forge start` command is executed

**Thanks for your help**

**Comment by luke-belton** [comment]
Hi @andres-mestra - we've [added improved handling](https://github.com/bugsnag/bugsnag-js/pull/1738) of a missing `apiKey` in [`v7.16.5`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.16.5) of `bugsnag-js`. Thanks for reporting!
