### ISSUE TITLE
Support Javascript Error.cause stacktrace unrolling / visualisation

### ISSUE THREAD

**Issue by aethr** [bugsnag/bugsnag-js#1674]
### Description
Our project uses error wrapping extensively to provide more fine-grained user experiences depending on what type of error occurred, and what the context was. When wrapping an error we use the new Error `options.cause` to retain the original Error object:

```js
try {
  await aRiskyManuever();
} catch (e) {
  throw new ManueverFailedError('it was not a success', { cause: e });
}
// full original Error with stacktrace will now be available in `error.cause`
```
This "official" way of wrapping an error is now supported in Chrome and node `v16` (the current LTS).

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Error

**Describe the solution you'd like**
It would be really useful if the Bugsnag stacktrace view somehow supported showing the stacktrace from each error in the `cause` chain (since an error can be wrapped multiple times).

As it stands, we only get to see the stacktrace/context around the final error that was thrown.

**Describe alternatives you've considered**
I believe there is a slightly hacky workaround available, that involves manually concatenating the stacktrace from each error in the chain into a single string that follows the "normal" stacktrace format. We could potentially try and do this in our own error handling system before the error hits the Bugsnag `notify` call.

I'll probably be looking into this in the short term, but I didn't want that to stop me requesting what I think would be a useful feature for Bugsnag moving into the future, as this is an "official" way that JS errors can be structured.

**Additional context**
node.js compatibility for `Error.cause`: https://node.green/#ES2022-features-Error-cause-property

**Comment by djskinner** [comment]
Thanks for bringing `Error.cause` to my attention, I was not aware of this existing in JavaScript at the time we rolled our own `CausedError` with similar functionality.

I believe other Bugsnag notifiers handle caused errors where the language supports it properly so it does make sense and would be a nice addition to add this to the JavaScript notifier now there is some sort of standard.

The good news is that Bugsnag has first-class support for caused errors and so I can offer you a better approach than concatenating stack traces - you can add an `onError` handler to attach each `Error.cause` as additional errors to the Bugsnag event, something like this:

```
// Return an array of the error cause stack.
export function getCauseStack(error: Error): Error[] {
  if (error.cause) {
    return [error, ...getCauseStack(error.cause)];
  } else {
    return [error];
  }
}

function attachErrorCauses(event: Event): void {
  // get all causes, skipping the original error
  const causes = getCauseStack(event.originalError).slice(1);

  const handledState = {
    unhandled: event.unhandled,
    severity: event.severity,
    severityReason: {
      type: 'unknown',
    },
  };

  causes.forEach((error) => {
    event.errors.push(Event.create(error, true, handledState, 'unknown', 0).errors[0]);
  });
}

Bugsnag.start({
  onError: [
    attachErrorCauses
  ],
  [...]
})
```

Doing it this way will give you a nicer experience in the dashboard where the main error and stacktrace is listed, followed by the "caused by" errors and their stacktraces beneath.

**Comment by aethr** [comment]
@djskinner this seems to be working well, with the one additional note that `Event` in your code snippet has to be imported from `@bugsnag/js`:

```js
import { Event } from '@bugsnag/js';
```

**Comment by djskinner** [comment]
Glad to hear it. I have updated my code snippet with your addition for the benefit of future travelers. Thanks again for bringing our attention to `Error.cause`. It's something I'm sure we'd like to bake into the JS notifier automatically at some point, as priorities allow.

**Comment by luke-belton** [comment]
Hi all - [we added support](https://github.com/bugsnag/bugsnag-js/pull/1759) for `Error.cause` in [`v7.17.0`](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.17.0) 🎉
