### ISSUE TITLE
Web Worker error notifying

### ISSUE THREAD

**Issue by jmshal** [bugsnag/bugsnag-js#172]
Right now you can technically catch errors from `Worker`s by listening to it's `onerror` event. However it seems (at a first glance) that the stacktrace is lost. It might be worth having an additional (tiny) script to import within a worker which basically proxies the error & stacktrace back to the main thread for it to notify (making the worker completely config-less).

I still have to see what's technically possible, but I'm pretty confident it can be done.

Thoughts?

**Comment by kattrali** [comment]
Thanks for the report, @jacobmarshall. Seems like kinda of a hairy issue, but I'm open to ideas. 🤔 @eanakashima @wordofchristian might also have some thoughts.

**Comment by jacobmarshall** [comment]
I think it would be very reliant on how #170 turns out.

**Comment by wordofchristian** [comment]
Does #170 solve the stacktrace problem, or is more required?

**Comment by jacobmarshall** [comment]
More is required, as the error needs to be caught from within the worker in order to extract the stacktrace. If you'd like I can combine this into #170?

**Comment by bengourley** [comment]
As with #170, we are going to pick this up in the next major.

**Comment by JacobEvelyn** [comment]
It appears that a major release has come and gone since that last ^ comment. Is this still planned?

**Comment by JacobEvelyn** [comment]
For anyone here who saw @jmshal's statement

> Right now you can technically catch errors from `Worker`s by listening to its `onerror` event.

and is wondering how to actually do that, I dug through the code for a while and eventually came up with this:

```javascript
worker.onerror = function(errorEvent) {
  const bugsnagReport = new bugsnagClient.BugsnagReport(
    "worker.onerror",
    errorEvent.message,
    [
      {
        fileName: errorEvent.filename,
        lineNumber: errorEvent.lineno,
        columnNumber: errorEvent.colno
      }
    ],
    {
      severity: "error",
      unhandled: true,
      severityReason: { type: "unhandledException" }
    }
  );

  bugsnagClient.notify(bugsnagReport);
};
```

Since the [`ErrorEvent` interface](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent) is used for [every error event _except_ for `window.onerror`](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror), I wonder if it makes sense to allow `Bugsnag.notify` to take an `ErrorEvent` and just change Bugsnag's `window.onerror` (which does not pass an `ErrorEvent`—see MDN doc) to `window.addEventListener("error", ...)` (which does). Thoughts?

**Comment by johnkiely1** [comment]
Hi all, just writing to let you know that we recently released support for Web Workers in bugsnag-js:
https://github.com/bugsnag/bugsnag-js/releases/tag/v7.20.0
 
You can read more about this in our docs:
https://docs.bugsnag.com/platforms/javascript/web-workers/

**Comment by LeSpec** [comment]
Finally i found out how to get bugsnag working in my firefox add-on background.js script:
@bugsnag/web-worker :thumbsup:
