### ISSUE TITLE
onUnhandledRejection missing from React Native

### ISSUE THREAD

**Issue by shamilovtim** [bugsnag/bugsnag-js#1816]
### Description

Unhandled promises are warnings. They are not crashes or exceptions. Bugsnag is treating them like "unhandled exceptions" which affects our stability score and makes it inaccurate. We care that the app is crashing, not that Promises haven't resolved successfully. 

**Describe the solution you'd like**

To make unhandled promises be considered "handled" exceptions we require the `onUnhandledRejection` callback. It is not available to us neither in the JS nor on the native platforms. 

**Describe alternatives you've considered**

The API surface on React Native is too minimal and does not provide us with many options to accomplish this a different way.

**Additional context**

Please consider enlarging the React Native JS API. It does not have many options like the JS API does and leaves us having to make feature requests on this repo.

**Comment by luke-belton** [comment]
Hi @shamilovtim - we mark uncaught promise rejections as `unhandled` in Bugsnag because the uncaught errors could potentially mask serious errors in your application code. We expose the `onUnhandledRejection` callback in Node because we replace the default `process.on('unhandledRejection')` handler, so have to mimic the default behaviour there.

That said, I'm going to pass your feedback onto our product team to see if there's anything we can do to make these types of error identifiable via a callback 👍

**Comment by johnkiely1** [comment]
Hi @shamilovtim, following some internal discussion we have added an item on the roadmap to expose the event type in a callback as way for you to achieve this. At the moment we don't have an ETA for this but we will keep you updated.

**Comment by clr182** [comment]
Hi @shamilovtim 

I just wanted to reach out with an update. 

We have just released a new version of the BugSnag-JS notifier. This new version of the notifier adds a new configuration option (`reportUnhandledPromiseRejectionsAsHandled`) and allows unhandled promise rejections to be reported as handled and not contribute to app stability scores.

You can find the update here: https://github.com/bugsnag/bugsnag-js/releases/tag/v8.1.2 

After updating to the latest version of the notifier, please let us know if you have experiencing any issues and we can investigate further.
