### ISSUE TITLE
Bugsnag request failed to complete

### ISSUE THREAD

**Issue by robsonsr** [bugsnag/bugsnag-js#1829]
### Describe the bug
When I run the command ./gradlew assembleDevelopmentRelease I get this error:

> Task :app:bugsnagReleaseDevelopment-releaseTask FAILED
Bugsnag: Uploading to Releases API

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:bugsnagReleaseDevelopment-releaseTask'.
> java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Bugsnag request failed to complete

It only work  when I use sudo:
sudo ./gradlew assembleDevelopmentRelease 

### Steps to reproduce
1.  ./gradlew assembleDevelopmentRelease (build apk)

### Environment
* Bugsnag version:   "@bugsnag/react-native": "7.17.4",

**Comment by johnkiely1** [comment]
Hi @robsonsr 

Would you be able to run the following `./gradlew clean assembleDevelopmentRelease --stacktrace --info `and send us the log output as it would be good to get a little more detail from the logs around when it fails. Feel free to send this to us via support@bugsnag.com instead of publicly posting it here. Thanks

**Comment by johnkiely1** [comment]
Hi @robsonsr. 

Going to close this out as we haven't heard from you. We would need some more information to help investigate. Happy to reopen as necessary.
