### ISSUE TITLE
 Uncaught ReferenceError: __show__deepen is not defined

### ISSUE THREAD

**Issue by radiofrequency** [bugsnag/bugsnag-js#186]
I'm getting this exception thrown on:
UC Browser version 11 and 10 on android 4 and 5.

Is this a problem with bugsnag?

stack trace:
../js/bugsnag.js:619	
            file: url,
            lineNumber: lineNo,
            columnNumber: charNo,
            stacktrace: (exception && stacktraceFromException(exception)) || generateStacktrace(),
            severity: "error"
          }, metaData);
        }

**Comment by eanakashima** [comment]
Hi @radiofrequency, thanks for the report. I'd guess this is most likely not a problem with bugsnag-js, since we don't reference `__show__deepen` anywhere, but it's hard to definitively say what the cause is from the info here. The bugsnag-js library has to wrap some native functions to be able to reliably report exceptions across browsers, so it's normal for us to show up in the browser console or the stacktrace when an error happens, even though the underlying error is not caused by Bugsnag. If you want to send us a link to something in your dashboard to dig into it more, drop us a line at support@bugsnag.com?

**Comment by radiofrequency** [comment]
appreciate the response!  if i can't figure it out i'll email thanks!

**Comment by kdzwinel** [comment]
<img width="1263" alt="ucbug" src="https://cloud.githubusercontent.com/assets/985504/19268160/0ffaff66-8fb3-11e6-8911-be034250a232.png">

we get this error a lot and it comes almost exclusively from specific UC browser version. Looks like browser bug to me. Unfortunately UC doesn't have a public bug tracker AFAIK.

This thread is only google hit for this error so I'm leaving this info here for others.

**Comment by davidhariri** [comment]
Thanks @kdzwinel

**Comment by AmitM30** [comment]
We are getting the same error a lot, exclusively on UC browser 10|11, but Android version ranging from 4.4.4 to 6.0.1. Though am using some other tool for js error reporting. Will look to exclude this

**Comment by Samsy** [comment]
@davidhariri Would be awesome if you provide a link to your article ?

**Comment by nidhi-tandon** [comment]
Has anyone figured out the solution. Even I have recently saw this issue on 
UC Browser Version: 12.2.0
Android Version: 5.1.1.
