### ISSUE TITLE
@bugsnag/react-native automatic sourceMaps upload script for iOS is breaking build on XCode 15

### ISSUE THREAD

**Issue by xeroxoid** [bugsnag/bugsnag-js#2019]
### Describe the bug
After updating to Xcode 15 building the react native app on iOS fails on phase "Running script 'Upload source maps to Bugsnag'"

The error states:
```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Error: Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening MentorAIFusion.xcworkspace.".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

When we disable the script the build is successful again.

Workaround to temporary disable the script for development is to enable running script for install builds only:

![bugsnag](https://github.com/bugsnag/bugsnag-js/assets/1199451/404db6c0-3960-456d-8028-b9ff31fdb04d)

### Environment
Bugsnag versions:

dependencies:

    "@bugsnag/plugin-react-navigation": "^7.19.0"
    "@bugsnag/react-native": "^7.21.0"

dev dependencies:

    "@bugsnag/cli": "^1.2.2",
    "@bugsnag/source-maps": "^2.3.1",

Also FYI although v7.22 of bugsnag has been released for 3 weeks now it has not been published to npm.

**Comment by mclack** [comment]
Hi @xeroxoid,

After upgrading to Xcode 15, I am finding that the iOS React Native build process is not failing, and the source map upload script is still working as expected.

I’ve done some reading around the `error code 65` you are seeing. It seems like this can sometimes happen after upgrading Xcode, and is possibly due to some dependency issues/caching, particularly around Cocoapods.

I’d first recommend `cd ios && pod update` to see if this rectifies the issue. It doesn’t currently look like you are running your build directly from the Xcode app which would allow for some better debugging, so if you are still having issues, I’d suggest building within Xcode for some more thorough debug logs, and this might point towards the particular library that is causing the issue.

There seem to be various resolutions for this issue, so it might be worth searching the `Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65` error yourself, and checking if any suggestions seem particularly relevant to what you’re seeing.

If you still have no success, then we’d be happy to look at any further debug logs you receive from Xcode, and we might be able to make some suggestions.

In regards to version 7.22.0 of `bugsnag-js` not being available on npm, this is because we don't publish all the packages for all the releases. 7.22.0 just changed [@bugnsag/react-native-cli](https://www.npmjs.com/package/@bugsnag/react-native-cli), so that's all that was published.

**Comment by xeroxoid** [comment]
Hi @mclack ,

Thank you for the quick response.

I had already deleted all Pods and node_modules and build folders before I opened the issue, but did it again just to be sure and started fresh.

When running via XCode, it still seems that the problem lies with the particular Build Phase Script "PhaseScriptExecution: Upload source maps to Bugsnag"
![Screenshot 2023-10-05 at 15 38 12](https://github.com/bugsnag/bugsnag-js/assets/1199451/954d637f-1d85-4c8c-a1d6-a7f980b5975e)

The culprit seems to be that the script cannot evaluate the "CFBundleShortVersionString" which does indeed exist and is evaluated at build time via `$(MARKETING_VERSION)`
![Screenshot 2023-10-05 at 15 46 23](https://github.com/bugsnag/bugsnag-js/assets/1199451/5c8c7c65-ebcf-4f33-a0ed-46b13d9d36ba)

The fact that the build works for development when selecting to only run the build phase script for install builds (i.e. not development?) also points to the direction that the problem lies there.

The strange thing is that this happened after updating XCode to v15 (due to MacOS Sonoma), I did not have a problem before that.

Please let me know if there are any further logs or resources I can provide to help out finding the underlying issue.

**Comment by fahadhaque007** [comment]
We are also seeing the same issue after upgrading to xcode 15. I fixed temporarily by ticking the checkbox  for install build only but that doesnt work for release mode. Is there any solutions to this? Thanks in advance

![Screenshot 2023-10-09 at 5 36 28 PM](https://github.com/bugsnag/bugsnag-js/assets/138623799/9149962f-e27e-4197-8627-d9478fae19fe)

**Comment by fahadhaque007** [comment]
@xeroxoid  I got it fixed by adding the following line in input file. My Archive is working correctly now. Hope this helps someone. 

`$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`

![Screenshot 2023-10-10 at 12 18 35 PM](https://github.com/bugsnag/bugsnag-js/assets/138623799/f19e6693-a4a0-4438-8283-815be6c33593)

**Comment by xeroxoid** [comment]
On newer projects (I guess react-native uses a newer template) the Info.plist file is not generated and put inside the application bundle. It seems like the `INFO_PLIST=$BUILT_PRODUCTS_DIR/$INFOPLIST_PATH` inside `node_modules/@bugsnag/react-native/bugsnag-react-native-xcode.sh` is the culprit as it assumes that there is a Info.plist inside the build folder.

For the same reason adding the input file does not work, if it contains generated values such as `$(MARKETING_VERSION)` that is needed by the ruby script.

**Comment by xeroxoid** [comment]
@mclack any news on this?

**Comment by mclack** [comment]
Thanks for the update @xeroxoid 

We're glad to hear upgrading your React Native version resolved this. We will take note of this in case we hear similar issues reported in the future.

Please feel free to reach out again if you need assistance with anything else.

**Comment by sparga** [comment]
I had the same error with react-native 0.72.6 after I started using Xcode 15 and wanted to share my solution here in case it helps someone in the future.

It turns out that the `Info.plist` is created later in the build process when you have app extensions. With Xcode 14, the plist exists after the `Copy Bundle Resources` build phase.

With Xcode 15, it's created after the `Embed App Extensions` build phase.

The solution was to move the `Upload source maps to Bugsnag` build phase after the `Embed App Extensions` one.

**Comment by phuongwd** [comment]
> @xeroxoid I got it fixed by adding the following line under _input files_. My Archive is working correctly now. Hope this helps someone.
> 
> `$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`
> 
> ![Screenshot 2023-10-10 at 12 18 35 PM](https://private-user-images.githubusercontent.com/138623799/273733648-f19e6693-a4a0-4438-8283-815be6c33593.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MzUxNjUsIm5iZiI6MTcwODczNDg2NSwicGF0aCI6Ii8xMzg2MjM3OTkvMjczNzMzNjQ4LWYxOWU2NjkzLWE0YTAtNDQzOC04MjgzLTgxNWJlNmMzMzU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQwMDM0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOTYxM2RkYmIzMDdlZjgxOTUyM2Q3OTg0ZjllZTMzZjFlMDNhZjZlOTQyMzU1OWQ0YTgwMjJlYjFkMWQ5NjVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kjVNm5YV_3yksGiC9jECXc439KBiZYmkVgEth6RyXFo)

Thanks @fahadhaque007 

```
System:
    OS: macOS 14.2.1
  IDEs:
    Xcode: 15.2/15C500b - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.13 => 0.71.13 
   @bugsnag/source-maps": "^2.3.1
```
