### ISSUE TITLE
Suppress info logs

### ISSUE THREAD

**Issue by pvarouktsis** [bugsnag/bugsnag-js#2066]
Is there a way to suppress info logs like this one `[bugsnag] Breadcrumb not attached due to onBreadcrumb callback` without configuring the whole logger?

**Comment by clr182** [comment]
Hi @pvarouktsis 

Out of interest, are you interested in blocking all Breadcrumbs from being sent to BugSnag via an `onBreadcrumb` callback?
If so, it's worth noting that if you wish to disable breadcrumb capturing you can do so by utilizing the `enabledBreadcrumTypes` setting in your BugSnag configuration. 
You can read more about this setting here: https://docs.bugsnag.com/platforms/javascript/configuration-options/#enabledbreadcrumbtypes

Otherwise, could you please share some further information on the `onBreadcrumb` callback you have implemented?

**Comment by pvarouktsis** [comment]
Hey @clr182

I have implemented a callback where I filter the Breadcrumbs
```
export const initBugsnag = () => {
  Bugsnag.start({
    plugins: [new BugsnagPluginReactNavigation()],
    onBreadcrumb: breadcrumb => {
      const isBackendRequest = BackendRequestBreadcrumbSchema.safeParse(breadcrumb);
      if (isBackendRequest.success) {
        return false;
      }
      const isReactNavigation = ReactNavigationBreadcrumbSchema.safeParse(breadcrumb);
      if (isReactNavigation.success) {
        return false;
      }
      return true;
    },
  });
};
```
but in this case it logs ` DEBUG  [bugsnag] Breadcrumb not attached due to onBreadcrumb callback` for every Breadcrumb filtered.

I found out that I can config the logger but I must do it for all the log levels (error, warning, etc.). Like this
```
export const initBugsnag = () => {
  Bugsnag.start({
    plugins: [new BugsnagPluginReactNavigation()],
    onBreadcrumb: breadcrumb => {
      const isBackendRequest = BackendRequestBreadcrumbSchema.safeParse(breadcrumb);
      if (isBackendRequest.success) {
        return false;
      }
      const isReactNavigation = ReactNavigationBreadcrumbSchema.safeParse(breadcrumb);
      if (isReactNavigation.success) {
        return false;
      }
      return true;
    },
    logger: {
      debug: (message: string) => {
        if (message.includes('Breadcrumb not attached due to onBreadcrumb callback')) {
          return;
        }
        console.log('Bugsnag info:', message);
      },
      info: (message: string) => {
        console.log('Bugsnag info:', message);
      },
      warn: (message: string) => {
        console.warn('Bugsnag warn:', message);
      },
      error: (message: string) => {
        console.error('Bugsnag error:', message);
      },
    },
  });
};
```

Is there a way to update only the debug log?

**Comment by mclack** [comment]
Hi @pvarouktsis 

We don't have granular configuration for every kind of log message. If you opt in to logging you get them all, and as you've already noted, you would need to define your own `logger` with `debug`, `info`, `warn` and `error` methods in order to override the default behaviour and filter out that particular log: https://docs.bugsnag.com/platforms/javascript/configuration-options/#logger

This should allow you to filter out the logs you don't want, so I'm going to close this issue. If you do have any particular problems with this then please feel free to reopen the issue, or you can open a ticket with us directly by contacting support@bugsnag.com
