### ISSUE TITLE
createErrorBoundary get error "Cannot read properties of undefined (reading 'prototype')" in Nextjs 14

### ISSUE THREAD

**Issue by chiennv97fenik** [bugsnag/bugsnag-js#2087]
I'm integrate bug snap for project Nextjs 14, but I getting issue

File: layout.js

```
import Bugsnag from "@bugsnag/js";
import BugsnagPluginReact from "@bugsnag/plugin-react";
import React from "react";
...
Bugsnag.start({
    apiKey: "e28a53d75b1907b8076ad881d0aacdb3",
    plugins: [new BugsnagPluginReact()],
  });
 const ErrorBoundary = Bugsnag.getPlugin("react").createErrorBoundary(React);
```

Error: Cannot read properties of undefined (reading 'prototype')

Please Help me

**Comment by clr182** [comment]
Hi @chiennv97fenik 

Thank you for reaching out. 

It's possible that this error has been caused by a race condition when rendering a component returned from `getPlugin` - which may happen before calling `Bugsnag.start`

However we are unable to verify this without further investigation, could you please provide the full error log for the error `Cannot read properties of undefined (reading 'prototype')` ?

**Comment by nicholas-masini** [comment]
For future reference, I just faced this same issue today and the solution is to initialise Bugsnag in a Client component instead of a Server component. My approach was to create a client component which is rendered inside the top-most layout.tsx file of the app router, and this client component will contain all the initialisation code for Bugsnag and various other providers that are used in my application.

**Comment by aleks-gentux** [comment]
so what do we do when the error is on server side? how come version 6 of bugsnag works fine on server side in nextjs, but version 8 doesn't?

**Comment by mclack** [comment]
Hi @aleks-gentux 

BugSnag does not officially support Next.js, particularly when it comes to the server side. Due to this, we can't make any guarantees on how well the notifier will work with Next.js. We do have an [example app](https://github.com/bugsnag/bugsnag-js/tree/next/examples/js/nextjs) as a supplement to the docs which aims to exhibit the simplest integration with the framework.

Please note that we also cannot guarantee that the example will be kept up-to-date, but viewing this along with a bit of extra context [here](https://github.com/bugsnag/bugsnag-js/issues/811#issuecomment-715329581) may be a good starting point to understand some of the known limitations.

We do have an item on our backlog to investigate what dedicated support for Next.js on the server side would require, but we don't currently have an ETA on when this may be looked into properly. If we have anything more to share on this, then we'll make sure to post on the linked issue, so we'd recommend subscribing to notifications on that thread for future updates: https://github.com/bugsnag/bugsnag-js/issues/811

**Comment by jpedroschmitz** [comment]
Any news regarding an integration with Next.js? @mclack 

I've been trying to integrate with it and having so many issues. Patching packages because of old and unresolved issues (https://github.com/bugsnag/bugsnag-js/issues/2189), rewriting stack frames, figuring out source maps upload/delete, and so much more. Honestly, it's such a huge pain.

**Comment by hannah-smartbear** [comment]
Hi @jpedroschmitz, 

Sorry to hear you’ve been having issues using BugSnag with your Next.js app. Unfortunately I don’t have any updates to share, but if you have any questions or issues that aren’t related to [the limitations described above by my colleague Milo](https://github.com/bugsnag/bugsnag-js/issues/2087#issuecomment-2754851889), e.g. help with deleting source maps, then feel free to open a new GitHub issue or reach out to us at [support@bugsnag.com](mailto:support@bugsnag.com) and we’d be happy to help.
