### ISSUE TITLE
Can't report error coming from Android(React Native) release build

### ISSUE THREAD

**Issue by cloudy-ninja** [bugsnag/bugsnag-js#2230]
### Describe the bug
Reporting an error on debug mode is working as expected and we can find it on the Bugsnag dashboard, but not on the release build. It looks like sending bugs to bugsnag works but can't see those on bugsnag dashboard only in release mode.

### Steps to reproduce
The following is the code block to notify an error 
```
<Button
  title="Report error to Bugsnag"
  onPress={() => {
    const estDate = new Date().toLocaleString('en-US', {
      timeZone: 'America/New_York',
    });
    Bugsnag.notify(
      new Error(
        `Test error coming from ${ENVIRONMENT}: ${pkg.version} - ${estDate}`,
      ),
    );
  }}
/>
```

### Environment
* Bugsnag version: 7.25.1
* React Native version: 0.72.6
* Android Gralde version: 8.0.1

* Device
    * Android Emulator
    * S22 Ultra

### Android Studio Logs when clicking on the **_Report error to Bugsnag_** button 
![Screenshot 2024-10-17 at 11 02 34](https://github.com/user-attachments/assets/9dddc0be-00f1-4b86-b694-ca1b6e8c7bfc)

**Comment by cloudy-ninja** [comment]
I was able to reproduce this issue with a fresh project. 
The steps to reproduce

1. @react-native-community/cli@latest init AwesomeProject
2. Added @bugsnag/react-native 8.0.0 
3. we can receive the incoming errors in debug mode on the Bugsnag dashboard but not in release mode.

**Comment by RobertoSmartBear** [comment]
HI @cloudy-ninja,

I see you are already in contact with our support with the same request. I have reported your last comment to our engineers but, just to avoid confusion, we will go on with the troubleshooting on the ticket and then publish the result here, once resolved.

**Comment by mclack** [comment]
Hi @andrei-tofan 

The latest version of our React Native SDK is not yet compatible with [bugsnag-android v6.10.0](https://github.com/bugsnag/bugsnag-android/releases/tag/v6.10.0). Due to this, we would recommend not overriding the version of `bugsnag-android` within your `build.gradle`, and instead let the dependency resolve to v6.6.1, as defined in the `bugsnag-js` package: https://github.com/bugsnag/bugsnag-js/blob/c80842fce5b01cce8e2b61e405d19aa0564ff28f/packages/react-native/android/build.gradle#L48

If you continue to have issues after using the latest compatible version of `bugsnag-android`, please feel free to open a ticket with us directly by contacting support@bugsnag.com, along with any relevant information for our further investigation (such as your version of `bugsnag-js` + `bugsnag-android`, any error messages, code snippets of BugSnag config + `build.gradle` dependencies etc), and we'll be happy to look into it for you.

**Comment by hannah-smartbear** [comment]
Hi @cloudy-ninja, 

> I see you are already in contact with our support with the same request. I have reported your last comment to our engineers but, just to avoid confusion, we will go on with the troubleshooting on the ticket and then publish the result here, once resolved. 

We haven't received a response on the support ticket for a while, so we are closing this GitHub issue alongside the support ticket. If you are able to get back to us on the support ticket then we'd be happy to reopen this.
