### ISSUE TITLE
Known performance issues?

### ISSUE THREAD

**Issue by FezVrasta** [bugsnag/bugsnag-js#244]
I'm debugging slowness in our application and as soon I replaced the bugsnag script URL with a URL pointing to an empty script the app performance dramatically improved.

Are you aware of any performance bottlenecks or issues with this script and React applications?

**Comment by eanakashima** [comment]
@FezVrasta thanks for the report. There aren't any known performance issues that I can think of that would create the situation you've described. It does seem possible that some sort of interaction with another script on the page (maybe another 3rd-party one?) could create performance issues. Is there a place where we could see a public version of the application so we can investigate? Feel free to email us at support@bugsnag.com if you would rather discuss privately. Thanks!

**Comment by FezVrasta** [comment]
I'll get back if we definitely narrow down the problem to Bugsnag, thank you.

**Comment by FezVrasta** [comment]
We had some unexpected `mousemove` events that triggered a lot of React updates, once we fixed this problem, the performances seem the same with or without bugsnag.

Could Bugsnag tried to intercept those events in some way?

**Comment by eanakashima** [comment]
That's interesting. We definitely don't listen for mouse movement events, unless you've instrumented something custom in your app to record these in Bugsnag as breadcrumbs. The only mouse events we listen for are clicks, and only if you have breadcrumbs enabled (on by default in v 3.x). We also listen for some navigation-related events, but it doesn't seem like those would be the issue here.
