### ISSUE TITLE
v4 errorClass vs. errorMessage

### ISSUE THREAD

**Issue by rokerkony** [bugsnag/bugsnag-js#278]
Hi, after update to v4 I wanted to accomplish the same logging result but it is quite "hacky". How can we set `errorClass` and `groupingHash` from `notify` method?

Our v3 implementation was:
`bugsnag.notify(errorClass, errorMessage, data, 'error');`

### Expected behavior
There should be probably some parameter in the notify method or as a field in opts to set `errorClass` and `groupingHash`.

### Version
v4.0.0

### Additional information
What I do currently is that I set the `errorMessage` even as an empty string (first param of `notify` method) and in `beforeSend()` I modify `errorClass` and add a `groupingHash` if provided in data.

```ts
notify (consoleSeverity: BugsnagSeverity, errorName: string, data: object, message?: string): void {
    this.bugsnagClient.notify(
        message || '',
        {
            beforeSend: (report: Report): void => {
                report.errorClass = errorName;
                if (report.metaData.hasOwnProperty('groupingHash')) {
                    report.groupingHash = (<any> report.metaData).groupingHash;
                }
            },
            metaData: {...data},
            severity: consoleSeverity,
        },
    );
}
```

**Comment by bengourley** [comment]
You can do `bugsnagClient.notify({ errorClass: 'Error', errorMessage: 'your message here' })`.

`groupingHash` can only be set via `beforeSend` callback though.

**Comment by rokerkony** [comment]
ohh, thx

I looked to the implementation of `normaliseError()` and it would be nice then to extend a ts definition from `error: any` in:
```ts
public notify(error: any, opts?: INotifyOpts): boolean;
```
to something like:
```ts
export interface ErrorObject1 {
    name: string;
    message: string;
}
export interface ErrorObject2 {
    errorClass: string;
    errorMessage: string;
}
export type ErrorType = string | number | boolean | ErrorObject1 | ErrorObject2 | any;
...
public notify(error: ErrorType, opts?: INotifyOpts): boolean;
```

It could be still improved as there are 2 "glitches":
1. `any` has to stay to handle `isError()`
2. There should be actually 4 `IErrorObject*` interfaces to handle all combinations possible in the code, but it should be fine to handle the inputs reasonably

Do you think it would be ok to create a PR for it?

**Comment by bengourley** [comment]
My thoughts around this are…

- since `any` will always be allowed (it needs to be, for the reason you mentioned and things like the [angular error handler](https://github.com/bugsnag/bugsnag-angular/blob/e85d65f49f225bdfc82db815dcc9f833f56b284f/src/index.ts#L8), my understanding is that the addition of the other types here are to provide editor support and helping suggest the correct usage?
- if so, I think we should have the following definition: `ErrorType` can be
  - an instance of `Error`
  - `{ name: string; message: string; }`
  - `{ errorClass: string; errorMessage: string; }`
  - or `any`

I want the types to help users make the correct choice, and these are the most correct ways to use `notify()`… passing primatives is supported but it's not as useful so I want to guard against that if possible. What do you think?

If you don't see any problem with that, I'd gladly welcome a PR 👍 Glad to have another perspective on the Types also. Thanks

**Comment by rokerkony** [comment]
@bengourley I created a PR, let's move the discussion there if necessary. I totally agree with encouraging to use only recommended objects (therefore omit scalar values).

**Comment by toxaq** [comment]
Just so I'm clear, the reason for using `any` is so you can do runtime rejection of objects not listing in this library?

    function isError(value) {
      switch (Object.prototype.toString.call(value)) {
        case '[object Error]': return true;
        case '[object Exception]': return true;
        case '[object DOMException]': return true;
        default: return value instanceof Error;
      }
    }
 
If so, as one of the primary points of typescript is to avoid runtime errors, this choice seems backwards to me. You give up compile time type checking for runtime type checking with soft failure.
