### ISSUE TITLE
report.request is empty inside of beforeSend

### ISSUE THREAD

**Issue by andrewjaanuu** [bugsnag/bugsnag-js#294]
### Expected behavior
report.request has url and ip inside of beforeSend

### Observed behavior
report.request is empty inside of beforeSend

### Steps to reproduce
throw new Error('message'); inside of a script tag within a page.

### Version
d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by bengourley** [comment]
Hi @andrewjaanuu, thanks for the report!

First off, you'll never see `request.ip` in a `beforeSend` callback – this is because the browser has no access to the device IP, and so can't set it. The IP is added by Bugsnag's server when it receives the event.

However, you _should_ see `report.request.url`. I looked into this and it's because the internal `request` plugin __pushes__ a `beforeSend` callback which will run after any user supplied callbacks…

https://github.com/bugsnag/bugsnag-js/blob/55a5c662097667bb2d5ce19cc7e01e3b3204dd57/browser/plugins/request.js#L6-L9

The solution to this should be to `shift()` the callback onto the front of the array, so that the data is available to the user supplied callbacks. This change should also be applied to the internal `device` and `context` plugins.
