### ISSUE TITLE
React 16 error running tests says I'm running Node 

### ISSUE THREAD

**Issue by weklund** [bugsnag/bugsnag-js#330]
### Expected behavior
* Tests to pass when trying to render my top level App component without crashing

### Observed behavior
* App test fails and invokes a Node error message saying I need to use 'bugsnag' package for node based applications

### Steps to reproduce
* Clone Create-React-App
* Follow steps to integrate react from [Bugsnag React Docs](https://docs.bugsnag.com/platforms/browsers/react/) for 'bundled' integrations
* Create test that checks if App.jsx will render properly
* Npm run test

![](https://puu.sh/zCAYY/4b67f3d73f.png)

### Version
* NPM : 5.6
* React : 16.2
* Bugsnag-js: 4.3
* Bugsnag-react: 1.0.1

**Comment by bengourley** [comment]
Hi @weklund. Try putting Bugsnag in your `index.js` rather than your `App.js(x)`, that way it won't get loaded when you try to run your component tests. The component tests run in a node process (not a browser-like environment) and that is why bugsnag-js is warning you. Also you probably don't want Bugsnag running in your unit tests anyway!

Let me know how you get on with that.

**Comment by weklund** [comment]
@bengourley That was it!  Good call.
