### ISSUE TITLE
Browser freezes when exception is thrown

### ISSUE THREAD

**Issue by Moulde** [bugsnag/bugsnag-js#337]
The reason i post it here instead of the bugsnag-angular project, is because the last i see in the console is from bugsnag.js in the log, but it may be completely unrelated...
I can post the issue on bugsnag-angular if this is not the correct place.

### Expected behavior
I added a text exception:
`throw Error('test exception'); `
in my anuglar application component ngInit method, and expect the application to fail, and then send the error to bugsnag via the angular exception handler.

### Observed behavior
Instead my browser freezes, and the last thing i see in the console is:

```
  | decirc | @ | bugsnag.js:1955
-- | -- | -- | --
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | decirc | @ | bugsnag.js:1955
  | stringify | @ | bugsnag.js:1920
  | _$payload_25 | @ | bugsnag.js:1965
  | sendReport | @ | bugsnag.js:2048
  | notify | @ | bugsnag.js:1208
  | BugsnagErrorHandler.handleError | @ | index.js:33
  | (anonymous) | @ | core.js:5914
  | ZoneDelegate.invoke | @ | zone.js:388
  | Zone.run | @ | zone.js:138


```

### Steps to reproduce
I followed the guide on how to integrate bugsnag in angular, and it works fine when i throw an exception in the mentioned component **constructor**, but when I do it in the ngInit method, it freezes the app completely, this happens in both safari and chrome.

The bugsnag notify method example, from the docs, also works fine.

### Version
    "bugsnag-angular": "^2.0.0",
    "bugsnag-js": "^4.4.0",

Thanks :)

**Comment by Moulde** [comment]
It seems that an exception in the ngOnInit function in angular, is bad for business, but before I included bugsnag.js and bugsnag-angular, it would just break routing, and you'd have to reload the page. But after including bugsnag, it completely freezes the browser tab, and you'd have to resort to the chrome task manager to close the tab, and I havent found a way to close the tab in safari.,

This sounds more and more like something i should take up with the bugsnag-angular project instead...

**Comment by bengourley** [comment]
Hi @Moulde. Thanks for posting this, sorry that it's causing issues for you. It appears to be the same issue as this one: https://github.com/bugsnag/bugsnag-angular/issues/3.

You are right to post the issue here (on bugsnag-js), as the root cause is the "fast-safe-stringify" module we're using in this module doesn't quite remove all circular references, or perhaps in your case it's running out of resources with a very deeply nested object.

We're working on a fix, and I'll ensure that whatever we do works on circular structures _and_ your particular example of throwing an error in `ngInit`. I will try to reproduce your issue but may need to come back to you for more info, so perhaps you could provide some example code that demonstrates the bug?

I'll keep you updated. Thanks!

**Comment by bengourley** [comment]
Hi @Moulde. Please upgrade bugsnag-js to v4.6.0. We completely replaced the JSON serialisation component and you should now be protected against deep/wide/circular structures. Let us know how you get on! Thanks.
