### ISSUE TITLE
unhandled promise rejection 

### ISSUE THREAD

**Issue by patrickomeara** [bugsnag/bugsnag-js#398]
### Expected behavior
The error should be reported to bugsnag

### Observed behavior
The error is reported in console but bugsnag is not notified.

unhandled errors outside of promises are being reported fine.

### Version
v4.7.3

### Additional information
```
[bugsnag] Loaded! bugsnag.js:1071
XHR OPTIONS https://sessions.bugsnag.com/
[HTTP/2.0 200 OK 343ms]
XHR GET https://localhost/v1/me/notifications
[HTTP/2.0 200 OK 4088ms]
XHR POST https://sessions.bugsnag.com/
[HTTP/2.0 202 Accepted 215ms]
XHR POST https://localhost/v1/me/notifications/read
[HTTP/2.0 200 OK 293ms]
Unhandled promise rejection TypeError: "t.notifications.count is not a function"
```

**Comment by bengourley** [comment]
Which browser is this? Firefox doesn't currently call the `onunhandledrejection` handler.

Chrome and Edge support this behaviour, but Firefox's implementation of it can be tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1362272

I'm closing because this isn't something the notifier can hook into unless the browser supports it. Note that if you use a promise lib such as bluebird, the unhandledrejections do get to bugsnag.

**Comment by patrickomeara** [comment]
Yep, this is Firefox. That's interesting about bluebird, I'll look at implementing it. Thanks @bengourley
