### ISSUE TITLE
bugsnag-js does not pick up development environment from NODE_ENV

### ISSUE THREAD

**Issue by robjbrain** [bugsnag/bugsnag-js#413]
### Expected behavior
In the docs it says:

> By default, if the URL contains localhost this is set to development, otherwise it takes the value from process.env.NODE_ENV. The default value in all other circumstances is production.

But my errors are always coming through as production.

### Observed behavior
I put this in my app.js file as a test:

```
import bugsnag from 'bugsnag-js'
import bugsnagVue from 'bugsnag-vue'
const bugsnagClient = bugsnag('xxx')
bugsnagClient.use(bugsnagVue(Vue))
console.log(bugsnagClient.notify(new Error('I am in development')))
console.log(process.env.NODE_ENV);
```

The response was:

`true`
`development`

But the error came through as "production" in the bugsnag dashboard.

Since `process.env.NODE_ENV` is printing `development` I assume the issue is with bugsnag somewhere?

### Steps to reproduce
I am using Laravel and Laravel Mix, to write down the steps to set that up in here would be a bit much.

I am using `npm run watch` with sourceMaps enabled.

This is equivalent to running:

`npm run cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

I am also using this alongside `bugsnag-vue`

I am also using this on a ".test" domain name running on Vagrant.

### Version
bugsnag-js 4.7.3
bugsnag-vue 1.0.1
laravel 5.7
laravel-mix 2.1

### Additional information
Related although slightly different. Since you recognise "localhost" as dev domain you should probably recognise all dev domains namely .test, .example, .invalid and .localhost as described here: https://tools.ietf.org/html/rfc2606 (although this is probably better as a separate feature request)

**Comment by robjbrain** [comment]
Also possibility related, but possibly not, bugsnag is not picking up my sourcemaps either even though source maps exist with my bundled js file. Potentially something in my setup is causing both issues?

**Comment by bengourley** [comment]
Hey @robjbrain, sorry we didn't get around to this. My colleague has responded to your support ticket, but for anyone else who find this thread…

This feature was [removed](https://github.com/bugsnag/bugsnag-js/commit/63e6019602efe10fb3d07c7b7354d72771177966#diff-e842c15dcdeda09f8b1937db40728227) because it dramatically increased the bundle size for all users, yet it is trivial to implement in user space for those who do want it. Here's how:

To define `NODE_ENV` (if it isn't already) in your Webpack bundle use the Webpack [define](https://webpack.js.org/plugins/define-plugin/) plugin (which is built in) in your `webpack.config.js`. Laravel Mix seems to do this for you.

```js
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
})
```

Then reference that value in your Bugsnag configuration:

```js
var bugsnagClient = bugsnag({
  apiKey: 'YOUR_API_KEY',
  releaseStage: process.env.NODE_ENV
})
```

We'll update the docs so they're correct.

Also thanks for the suggestion about other dev domains. I'll add to our internal roadmap something to get that looked into.

**Comment by bengourley** [comment]
[The docs](https://docs.bugsnag.com/platforms/javascript/configuration-options/#releasestage) have now been updated.
