### ISSUE TITLE
SRI Support

### ISSUE THREAD

**Issue by edent** [bugsnag/bugsnag-js#414]
### Expected behavior
Clients should be able to use SubResource Integrity to ensure that the JavaScript has not been altered.

### Observed behavior

A user integrating bugsnag into a website, should be able to use [SRI](https://www.srihash.org/)
```
<script src="https://d2wy8f7a9ursnm.cloudfront.net/v4.1.0-1/bugsnag.min.js" 
   integrity="sha256-..............="
   crossorigin="anonymous"></script>
```

### Version
All

### Additional information

This is also mentioned on #155 

SRI is important to stop malicious users from corrupting a script.  The recent Magecart exploit was caused by websites including external scripts and not checking that they had been altered.

**Comment by bengourley** [comment]
This seems like a good idea to support. What would you need us to do (if anything)? As far as I can tell, this would have limited applicability because lots of our CDN users receive rolling updates, and so by that nature, the served file changes over time.

If you want to pin to a specific version of the script on the CDN, what is to stop you making your own digest to use in the `integrity` attribute, ensuring that the code does not change after you first retrieved it. Would you want us to publish the digest in a separate, trusted channel, so that you know that even the first time you retrieved it, it wasn't tampered with?

**Comment by edent** [comment]
I think the most important thing to do is to publicise it.  For example, on https://docs.bugsnag.com/platforms/browsers/js/ make sure that the SRI tag can be easily copied.

**Comment by RichiCoder1** [comment]
^ This. It would be great if exact versions (aka `<script src="//d2wy8f7a9ursnm.cloudfront.net/v6.0.0/bugsnag.min.js"></script>`) had either their hash documented somewhere or the full snippet logged somewhere like:
```html
<script
    src="//d2wy8f7a9ursnm.cloudfront.net/v6.2.0/bugsnag.min.js"
    integrity="gbIPoWuvU9CLyDBhsd9yDWYiih7NmWOSCAfoAO5j/wvSrPv/Q4hWnYEcZVH2VJHh"
    crossorigin="anonymous" />

**Comment by bengourley** [comment]
Closing this off as it requires effort and changes to our CDN that we can't commit right now.

The primary use case for our CDN is rolling updates. If you care about resource integrity you can already [install `@bugsnag/js` with a package manager](https://docs.bugsnag.com/platforms/javascript/#npm-recommended) that supports lockfiles.

Both the main npm client and yarn store a hash of the module in their lockfiles when it is first installed – ensuring that subsequent downloads (on other developers' machines and deployments) are the same content.

If there is sufficient demand for this use case in the future we may reconsider, but for now we don't plan to support it.
