### ISSUE TITLE
How to set beforeSend after initialization

### ISSUE THREAD

**Issue by razagill** [bugsnag/bugsnag-js#467]
Due to our complex setup we cannot set `beforeSend` while initializing the bugsnag instance, we have to do it afterwards.

I tried using the `setOptions` method on the client instance but that doesn't set it correctly (the report object is not overwritten).

Currently I'm doing it like so:
```javascript
bugsnagClient.config.beforeSend.push((bugsnagBeforeSend));
```
Where `bugsnagBeforeSend` is just a parsing method that returns an overwritten report object.

However, I'm getting a type error on the above, naturally because it could be of type `BeforeSend` or `BeforeSend[]`. Is there a more preferred approach to do this? As I couldn't find anything in the docs.

bugsnag package: `@bugsnag/js (v5.1.0)`

**Comment by bengourley** [comment]
It's not really supported, you should do it initialisation if you can.

However, you can just do what you are currently doing. Once it is attached to `bugsnagClient.config` you can be sure that `beforeSend` is an array.

I assume you're getting an error because you're using TypeScript so you can just convince the compiler everything is fine, with something like:

```typescript
(bugsnagClient.config.beforeSend as BeforeSend[]).push(bugsnagBeforeSend)
```
