### ISSUE TITLE
SessionTracker prevents process shutdown

### ISSUE THREAD

**Issue by jacobwgillespie** [bugsnag/bugsnag-js#477]
`SessionTracker` starts a `setInterval` inside its start method:

https://github.com/bugsnag/bugsnag-js/blob/192f2f34631c8f97e7635efa869f2a3a08776258/packages/plugin-server-session/tracker.js#L14-L18

It does have a `stop()` method, but that method is not exposed or called from anywhere:

https://github.com/bugsnag/bugsnag-js/blob/192f2f34631c8f97e7635efa869f2a3a08776258/packages/plugin-server-session/tracker.js#L20-L23

This leaves an open handle and prevents the process from exiting, for example this will cause Jest tests to never exit.

Would it be possible to have a `.destroy()` or `.shutdown()` on the Bugsnag client object to shut down this internal interval?

This is what Jest reports with `--detectOpenHandles`:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      31 | }
      32 |
    > 33 | export let bugsnag = initBugsnag({
         |                                 ^
      34 |   apiKey: env('BUGSNAG_API_KEY', 'placeholder key'),
      35 |   appVersion: version.commit,
      36 |   logger,

      at SessionTracker.start (../node_modules/@bugsnag/node/plugin-server-session/tracker.js:16:24)
      at Object.init (../node_modules/@bugsnag/node/plugin-server-session/session.js:12:20)
      at BugsnagClient.use (../node_modules/@bugsnag/node/core/client.js:91:20)
      at ../node_modules/@bugsnag/node/dist/src/notifier.js:47:33
          at Array.forEach (<anonymous>)
      at Object._$notifier_24 [as default] (../node_modules/@bugsnag/node/dist/src/notifier.js:47:11)
      at Object.<anonymous> (src/index.ts:33:33)
```

**Comment by bengourley** [comment]
The [`unref()`]() function of timers prevents it from keeping the process from exiting in Node. However, I assume you're using Jest to run tests on browser code? But this session tracking is for Node servers. By default Jest runs tests in a jsdom environment.

The actual problem here is that Jest won't load the browser-specific code unless you pass the [`browser: true`](https://jest-bot.github.io/jest/docs/configuration.html#browser-boolean) option.

> Respect Browserify's "browser" field in package.json when resolving modules. Some modules export different versions based on whether they are operating in Node or a browser.

This is all assuming you're testing browser code. If you're testing Node code then something else is the matter. Let me know how you get on. Cheers!

**Comment by jacobwgillespie** [comment]
Thanks for the reply - totally missed the `.unref()` in there!

I am testing Node code as these are server tests and are run with `jest-environment-node`, so something else must be the matter, yep.

**Comment by bengourley** [comment]
I think the `--detectOpenHandles` implementation throws some false positives.

This test exists successfully because of `unref()`:

```js
test('the process does not hang', () => {
  setInterval(() => console.log('ding'), 1000).unref()
  expect(1).toBe(1);
});
```

But if you run it with `jest --detectOpenHandles` it says:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Timeout

      1 | test('the process does not hang', () => {
    > 2 |   setInterval(() => console.log('ding'), 1000).unref()
        |   ^
      3 |   expect(1).toBe(1);
      4 | });
      5 |

      at Object.setInterval (app.test.js:2:3)
```

What's more, with the following test Bugsnag does not keep the process alive:

```js
const bugsnag = require('@bugsnag/js')
const bugsnagClient = bugsnag('API_KEY')

test('the process does not hang', () => {
  expect(1).toBe(1);
});
```

But I get it to warn me when the `--detectOpenHandles` check is used.

I'm going to close this off as I don't think it's an issue with Bugsnag, but feel free to supply more info if you think it is.

**Comment by jacobwgillespie** [comment]
I haven't had a change to get a reproduction together, by in my case I have a lerna monorepo where the bugsnag client is a local shared package (shared between multiple apps).

So essentially:

**packages/bugsnag/index.ts**

```javascript
import bugsnag from '@bugsnag/js'
export const bugsnagClient = bugsnag('API_KEY')
```

**apps/server/app.ts**

```javascript
import {bugsnagClient} from '@local/bugsnag'

...
```

Something about that situation causes Jest to never exit - I don't believe this is `--detectOpenHandles` finding a false positive since the process legit will never exit.  I'll see if I can play around with things on my end to determine which step in that setup causes the issue.

I do think it has something to do with the Bugsnag SDK though - I have similar issues with the Elasticsearch SDK and with Knex, but in the case of both of those I am able to call `.shutdown()` in the `globalTeardown` Jest module, which allows the connection pools to release and the tests to exit.
