### ISSUE TITLE
TypeMismatchError in Edge 15

### ISSUE THREAD

**Issue by eliseumds** [bugsnag/bugsnag-js#487]
I've seen hundreds of reports in the Bugsnag panel for Edge 15.15063.0 with breadcrumbs like these:

![screen shot 2019-02-26 at 12 50 19](https://user-images.githubusercontent.com/640840/53381507-1975c580-39c5-11e9-960f-6270e6143a73.png)

Apparently it has something to do with wrong parameters passed to "fetch()".

**Comment by bengourley** [comment]
Hey @eliseumds, we haven't seen anything like this from any other users, which leads me to believe these are geniune errors that are happening in your application in that browser.

If you found the problem, posting the solution here might help other users if they hit the same thing. Otherwise If you still need help figuring this out, drop us a message at support@bugsnag.com and we can take a closer look at your dashboard. Thanks!
