### ISSUE TITLE
Crisp.chat SDK broken due to Bugsnag shimming/replacing setTimeout

### ISSUE THREAD

**Issue by laukstein** [bugsnag/bugsnag-js#580]
Can bugsnag capture errors without shimming any native prototypes or can I turn it off at least?

![grabillaem7096_oagrkw](https://user-images.githubusercontent.com/183966/60952347-c5300a00-a303-11e9-8398-53f68e52c371.png)

I recently get this response from Crisp.chat where wasn't able to get rid of this warning:

> After some checks, it appears that you have a shimmed method. It's `setTimeout`, you have to rename it on your side before use it with Crisp, otherwise there is shims and it can break Crisp script or even some thing on your website. 
> You have added this tool : https://www.bugsnag.com/
> That produces the `setTimeout` method.
> 
> When that will be resolve, all will be ok

https://github.com/bugsnag/bugsnag-js/blob/c5062506e74e7677b60dfd5af25ed5014dfcd76e/packages/plugin-inline-script-content/inline-script-content.js#L83-L104 shows many native prototypes you try to replace.

**Comment by bengourley** [comment]
Unfortunately this is the only reliable way to track inline scripts in order to report the surrounding code and line number when things go wrong.

If you need to stop patching all of the built-in functions, you can turn off the [`trackInlineScripts`](https://docs.bugsnag.com/platforms/javascript/configuration-options/#trackinlinescripts-browser-only) option.

As far as I can tell, what you're seeing is just a warning? Bugsnag _shouldn't_ alter the behaviour of these functions – it just captures some the execution trace and then forwards everything on to the original function. What happens if you do `$crisp.push(["safe", true])` like it suggests? Does it still break? If so, how?

**Comment by laukstein** [comment]
@bengourley, ` $crisp.push(["safe", true])` doesn't get rid the warning. I didn't notice any specific errors with Crisp. Their support team wrote that Bugsnag shouldn't replace setTimeout otherwise would break Crisp. I think Crisp might be trying to replace setTimeout too.
Can you maybe allow to define prototypes names not allowed to Bugsnag to change them, and document how it will affect code tracking?

**Comment by laukstein** [comment]
@bengourley, FYI `trackInlineScripts` doesn't work form JavaScript modules having extension **.mjs**

**Comment by bengourley** [comment]
> `$crisp.push(["safe", true])` doesn't get rid the warning.

That sounds like a bug with Crisp's SDK to me – the log message says that's what it should do.

There's not really anything for us to do here. We try to be as unobtrusive as possible, but for reliable inline script tracking this is what we need to do. And it sounds like Bugsnag is working for you. If our patched functions broke anything, we'd soon know about it!

> Their support team wrote that Bugsnag shouldn't replace setTimeout otherwise would break Crisp.

I think they are just trying to be defensive about the environment their script is running in. When you ship an SDK that loads on any kind of website, sometimes people modify built-in stuff in a non-compatible way. This is good advice most of the time but for a library like Bugsnag, sometimes we need to subvert best-practices to get things done.

> FYI trackInlineScripts doesn't work form JavaScript modules having extension .mjs

In what way is `trackInlineScripts: false` not working for you?

**Comment by laukstein** [comment]
@bengourley, Bugsnag doesn't show code snippets for **.mjs** files, but only for **.js**

**Comment by bengourley** [comment]
Ok. Since that's a different issue I'm going to close this off.

We may have just shipped a fix for this – previously our system wouldn't fetch source with the extension `.mjs` but it does now.

If you're still having problems with that, please can you email support@bugsnag.com and we'll help get it sorted?

**Comment by bengourley** [comment]
I see you already had a support thread!
