### ISSUE TITLE
Bugsnag stealing addEventListener on FireFox addon-ons

### ISSUE THREAD

**Issue by DJWassink** [bugsnag/bugsnag-js#607]
I am currently in the middle of working on a addon/plugin/extension that works in both chrome and firefox, however in firefox I noticed that bugsnag steals the `addEventListener` method which results in the event never firing. Setting a specific event directly on an element e.g. `div.onclick` still works.

I have created a repo with a very simple reproduction case.
1. clone https://github.com/DJWassink/bugsnag-addeventlistener-steal
2. yarn install
3. yarn build
4. load the addon in firefox (see: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)
5. go to https://developer.mozilla.org/ and scroll to the bottom for the pink div to appear (see attached screenshot)
6. Click on the div and nothing happends.

Now if you edit the `test.js` file and comment out the bugsnag require and initalization and run the `yarn build` command again, reload the extension in firefox, reload the page with the injection. Click on the pink square, it will show you an alert('hiya');

![image](https://user-images.githubusercontent.com/1822404/62361553-93cde700-b51b-11e9-8fc8-ac4293c06b66.png)

**Comment by abigail-bugsnag** [comment]
@DJWassink thank you for your comment. We have tried your example in a normal browser environment and were unable to reproduce the issue. We then tried this in an extension and have been able to reproduce the issue.
We will look into this in due course.

**Comment by bengourley** [comment]
Hey @DJWassink thanks for the report. I looked into this today and the way Bugsnag tracks inline scripts is unfortunately limited by the "[Xray Vision](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/Xray_vision)" feature of content scripts in Firefox extensions.

Bugsnag patches the `addEventListener` method on built-in prototypes (such as `EventTarget` which `HTMLDivElement` extends, which you are adding a click handler to).

The crux of the matter is this:

> page scripts cannot see JavaScript properties added by content scripts.

([source](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#DOM_access))

Since you are loading Bugsnag and adding your event handler in the "content script", the page (which dispatches the event) routes the event via the unpatched event listener mechanism and so it never reaches your callback.

The only thing you can do is set the option [`trackInlineScripts: false`](https://docs.bugsnag.com/platforms/javascript/configuration-options/#trackinlinescripts-browser-only). This will prevent any patching of built-in event handlers and async entry points, meaning that your content scripts and page scripts "see" the same state of DOM.
