### ISSUE TITLE
If internet goes out, Bugsnag slows down all requests 20x

### ISSUE THREAD

**Issue by bgold0** [bugsnag/bugsnag-js#628]
We have bugsnag on a server in a location where it has intermittent internet access. Our express server talks to a local database and only uses the internet to send bugsnag reports.

When there is internet, everything works as expected. However, when there is no internet and bugsnag needs to send a bug report, it intercepts all the requests and tries to send the bug report 10 times before it let's the request go through.

Essentially turning a 500ms call to a 10,000 - 15,000ms call.

**Steps for Reproduction:**
1. Turn Express server 100% offline.
2. Make standard request to see how many milliseconds it takes.
3. Create a bugsnag bug. In our case, we generated 4xx requests.
4. Now make the same request and watch that the request takes 20 times longer to complete
5. Turn internet back on.
6. Make same request a couple times, and watch the requests time speed up again
7. Rinse and repeat.

**Comment by abigail-bugsnag** [comment]
Hi @bgold0 thanks for the report!
We are looking into adding support for offline operation where error reports would be delivered when a connection is re-established.

**Comment by mattdyoung** [comment]
@bgold0 

We've started looking into whether we could fix the root cause of this slow down in advance of adding offline support.

We haven't so far been able to reproduce the behavior you describe though. We've tried setting up a test with an Express server with 30 parallel processes sending an error to the Bugsnag API 100 times in quick succession. We haven't been able to measure any difference in the time taken even when making the end-point unresponsive causing all API requests to timeout and fail.

Are you able to provide a reproduction case?
