### ISSUE TITLE
are error messages being suppressed in development?

### ISSUE THREAD

**Issue by danprince** [bugsnag/bugsnag-js#634]
Why am I seeing this message when bugsnag is running in development and shouldn't be catching errors (according to `notifyReleaseStages`).

```
[bugsnag] Session not sent due to releaseStage/notifyReleaseStages configuration
```

Image to show the lack of context with each log:

![image](https://user-images.githubusercontent.com/1266011/67230066-7a5e7c00-f434-11e9-8c34-e2bae70153f7.png)

Here's how it's configured:

```
import * as config from "../config";
import bugsnag from "@bugsnag/js";

export let client = bugsnag({
  apiKey: config.BUGSNAG_API_KEY_SERVER,
  releaseStage: config.NODE_ENV, // is "development"
  notifyReleaseStages: ["production"],
});
```

I might be misunderstanding how `notifyReleaseStages` works but I don't understand why bugsnag is printing anything at all here. If it's catching an error, it should also be logging the error. If there is no error, it shouldn't be printing anything about not sending the session.

Is there any way to actually just disable bugsnag entirely in development, without having to mock out the entire module so that manual calls to the client won't break?

**Comment by mattdyoung** [comment]
Hi @danprince 

The `notifyReleaseStages` option is designed to limit what is sent to Bugsnag rather than prevent capture of sessions or errors.

Your screenshot shows the capture of sessions (which are subsequently not sent to Bugsnag due to your configuration) so no error has been caught in that instance:
https://docs.bugsnag.com/platforms/javascript/#session-tracking

With your configuration, when `releaseStage` is set to `development` Bugsnag will still capture sessions and errors but the `notifyReleaseStages` setting will prevent those being reported to Busgnag, and will also prevent any manual calls to `notify` from reporting to Bugsnag.

In a similar way you can prevent error reports being sent to Bugsnag for more specific criteria by returning `false` from a `beforeSend` callback based on properties of the `report` object:
https://docs.bugsnag.com/platforms/javascript/customizing-error-reports/#disabling-error-reporting

There isn't a way to disable Bugsnag entirely in development other than wrapping the calls to initialize and notify Bugsnag. But Bugsnag is designed to have minimal performance impact and where possible to not modify underlying error handling behaviour, so there should be no issue with enabling Bugsnag and using `notifyReleaseStages` to prevent delivery of the captured errors.

If the `[bugsnag]` console logs are too noisy where you're preventing delivery of errors in development you can supply an alternative logger or switch off Bugsnag logging completely as shown here:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#logger

Thanks!

**Comment by Gregoirevda** [comment]
custom `logger` function receives an event with `Event not sent due to releaseStage/enabledReleaseStages configuration`
and `onError` isn't called.
How can I avoid sending all development errors while developing an application to BugSnag, but simply logging them in the console?

**Comment by luke-belton** [comment]
Hi @Gregoirevda - rather than using the `enabledReleaseStages` config option, you could implement your own `onError` callback. Something like this should work:
```
Bugsnag.start({
  apiKey: 'YOUR_API_KEY',
  releaseStage: 'development',
  enabledReleaseStages: ['development', 'production'], // don't exclude `development` events!
  onError: (event) => {
    if (event.app.releaseStage === 'development') {
      console.debug(event.errors[0]) // or whatever is of interest about the event
      return false; // discard the error
    }
  },
  // other config options
})
