### ISSUE TITLE
Question: how to integrate Bugsnag in a custom React ErrorBoundary?

### ISSUE THREAD

**Issue by Finesse** [bugsnag/bugsnag-js#638]
I use custom [error boundaries](https://reactjs.org/docs/error-boundaries.html) in my application. They are used in different parts of the page, have a beautiful look and a «retry» button. The proposed Bugsnag approach to wrap the whole application in the Bugsnag's error boundary won't work in my case because the errors are already caught by my error boundaries.

```jsx
function MyApp() {
  return (
    <div>
      <MyErrorBoundary>
        Column 1
      </MyErrorBoundary>
      <MyErrorBoundary>
        Column 2
      </MyErrorBoundary>
    </div>
  );
}

const ErrorBoundary = bugsnagClient.getPlugin('react')

ReactDOM.render(
  <ErrorBoundary> {/* Will never catch */}
    <MyApp />
  </ErrorBoundary>,
  document.getElementById('app')
)
```

So the question is: what is the correct way to add a Bugsnag error reporting to my custom error boundary component?

```jsx
class MyErrorBoundary extends React.PureComponent {
  state = {hasError: false};

  static getDerivedStateFromError(error) {
    return {hasError: true};
  }

  componentDidCatch(error, errorInfo) {
    // What to type here?
    // Maybe `bugsnagClient.notify(error)`? But how to send `errorInfo` too?
  }

  render() {
    if (this.state.hasError) {
      // You can render any custom fallback UI
      return 'My custom pretty error display with a retry button';
    }

    return this.props.children; 
  }

  retry() {
    this.setState({hasError: false});
  }
}
```

**Comment by Finesse** [comment]
The reverse engineering shows, that I can implement the component this way:

```js
import { formatComponentStack } '@bugsnag/plugin-react';

function notifyReactError(error, errorInfo) {
  const handledState = {severity: 'error', unhandled: true, severityReason: {type: 'unhandledException'}};
  const BugsnagReport = bugsnagClient.BugsnagReport; // bugsnagClient is the client you created during an initialization of Bugsnag
  const report = new BugsnagReport(error.name, error.message, BugsnagReport.getStacktrace(error), handledState, error);
  if (info && info.componentStack) {
    info.componentStack = formatComponentStack(info.componentStack);
  }
  report.updateMetaData('react', info);
  bugsnagClient.notify(report, { beforeSend });
}

class MyErrorBoundary extends React.PureComponent {
  // ...

  componentDidCatch(error, errorInfo) {
    notifyReactError(error, errorInfo);
  }

  // ...
}
```

It would be great if the `@bugsnag/plugin-react` package exports a function like `notifyReactError`.

**Comment by bengourley** [comment]
You should just be able to use the Bugsnag error boundary everywhere you use your own, but we would also recommend adding a top-level catch-all one too for any places in the tree that might be missed.

You can pass your own component to render as the `FallbackComponent` prop:

```js
<ErrorBoundary FallbackComponent={BeautifulErrorRetryComponent}>
  /* the rest of your tree */
</ErrorBoundary>
```

The `FallbackComponent` receives `{ error, info }` as its state.

Hope this helps!

**Comment by Finesse** [comment]
Unfortunately no because `FallbackComponent` doesn't receive a `retry` function prop for me to be able to implement a `retry` button. I expect the `retry` function to reset the `ErrorBoundary` error [state](https://github.com/bugsnag/bugsnag-js/blob/next/packages/plugin-react/src/index.js#L10) back to `null`.

**Comment by bengourley** [comment]
Ok – I understand the problem now, thanks for explaining. I'll add this feature request to our internal backlog.

**Comment by Finesse** [comment]
Also there should be a note that nested error boundaries must be integrated with Bugsnag too in the [documentation](https://docs.bugsnag.com/platforms/javascript/react/#basic-configuration)

**Comment by tomgreener** [comment]
I'm experiencing a related issue. It's not possible to use React Router to navigate to a different page from within a `FallbackComponent`. If the Bugsnag error boundary exposed a way to reset the error state back to false, I could listen to the browser history in my `FallbackComponent` and [clear the error state to allow navigation](https://stackoverflow.com/a/49341596).

**Comment by xander-jones** [comment]
Hey @tomgreener, we're looking into a mechanism to do what you will need to clear the error state. We're hoping it will be incorporated into one of our future releases. We'll post back here once it is released.

**Comment by Finesse** [comment]
Here is a version of the report function for Bugsnag v7:

```ts
// @ts-ignore
import {formatComponentStack} from '@bugsnag/plugin-react';
import React from 'react';
import bugsnagClient from '../bugsnag'; // bugsnagClient is the object you created during the initialization of Bugsnag

function notifyReactError(error: Error, info: React.ErrorInfo) {
  const handledState = {severity: 'error', unhandled: true, severityReason: {type: 'unhandledException'}};
  const event = bugsnagClient.Event.create(error, true, handledState, 'Error boundary', 1);
  if (info && info.componentStack) {
    info.componentStack = formatComponentStack(info.componentStack);
  }
  event.addMetadata('react', info);
  bugsnagClient._notify(event);
}
```

**Comment by mattdyoung** [comment]
> I'm experiencing a related issue. It's not possible to use React Router to navigate to a different page from within a `FallbackComponent`. If the Bugsnag error boundary exposed a way to reset the error state back to false, I could listen to the browser history in my `FallbackComponent` and [clear the error state to allow navigation](https://stackoverflow.com/a/49341596).

Fixed in [v7.1.0](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.1.0)

**Comment by Haraldson** [comment]
@bengourley Is exposing `notifyReactError` something Bugsnag would be open to?

I feel like I’m losing control implementing this with a proxied, blackboxed Bugsnag-flavoured ErrorBoundary and would rather just do

```js
componentDidCatch = (error, info) => notifyReactError(error, info)
```

in a vanilla one and have the component stack formatted for me, by Bugsnag, instead of relying on @Finesse’s hack above, even though it seems nice enough.

Reading the docs, it’s also quite unclear what arguments are provided to `onError` and which props are provided to `FallbackComponent`. Yes, it’s partially documented in this issue’s comments, but should be much easier to find.

Finally, and possibly the biggest reason for why I want to roll my own ErrorBoundary, is due to the timing of my `Bugsnag.start()` call is async, depending on network calls resolving, as that’s how my web client gets a hold of the API key from that environment’s variables. The official way of wiring this up just doesn’t make much sense to me.

**Comment by Haraldson** [comment]
@luke-belton Thanks for the reply! If I understand you correctly, this solves my main worries by me no longer having to manually construct a Bugsnag Error object, instead getting it provided to the callback function – in addition to me not needing to import and use the `formatComponentStack` function directly, because this processing is built into `addMetaData` when called with `'react'` as its first argument (?)

---

When it comes to the async part, I’m currently doing it like this because I want the app to be both agnostic and flexible enough to be able to receive new environment variables if they need to be changed for whatever reason. The app takes quite a long time to build, so instead of having to go through that whole process after applying such changes, it makes more sense that they are provided by the much thinner client server layer.

**Comment by luke-belton** [comment]
Hi @Haraldson - the `formatComponentStack` function is [only called internally](https://github.com/bugsnag/bugsnag-js/blob/8f5b22bba5082736b0bce814f5ab2318f6c16484/packages/plugin-react/src/index.js#L75) inside the Bugsnag Error Boundary, not when you make a call to `addMetadata`. As I said above if you're not using the Bugsnag Error Boundary, you'd need to implement something similar inside your own `componentDidCatch` hook in order to format the component stack in the same way.
