### ISSUE TITLE
Add a means to update the application version etc. asynchronously

### ISSUE THREAD

**Issue by birtles** [bugsnag/bugsnag-js#813]
Sometimes the application version can only be established asynchronously.

e.g. when fetching the information using [Web Extensions APIs](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/management/getSelf) with the v6 API I am currently doing this:

```typescript
browser.management.getSelf().then(info => {
  (bugsnagClient.app as any).version = info.version;
  if (info.installType === 'development') {
    (bugsnagClient.app as any).releaseStage = 'development';
  }
});
```

I'm not even sure how I should do this with the v7 API. Perhaps there should be an API for this that would also update the current session?

**Comment by mattdyoung** [comment]
@birtles 
The way it works now is by design, the reason being, what would happen to error reports that happen before that information is available? The reports would have no `appVersion` and no `releaseStage`.

Our recommendation for this would be to find a way to get that information synchronously.

Failing that, we would recommend starting Bugsnag as soon as that information is available.

One alternative would be to add this information in an `onError` callback. We allow modifications to `event.app` there:
```
onError: event => {
  event.app.releaseStage = releaseStage
  event.app.version = version
}
```

But that doesn't solve the issue of what happens for any events that occur before the information is available.

**Comment by birtles** [comment]
Hi Matt, yes I'm aware that prior to setting the version the information, it would be undefined. That is the expected and desired behavior since it simplifies debugging by alerting one to the fact that the error occurred prior to establishing the environment.

Configuring Bugsnag after establishing the version is not desirable since it would mean any errors encountered while establishing the version are lost.

I hope you will reconsider this request since I think it is reasonable. By point of comparison [Rollbar's API](https://docs.rollbar.com/docs/rollbarjs-configuration-reference#section--rollbar-global-) allows updating the configuration after the fact. (I am currently a paying customer of Bugsnag but only a free user of Rollbar. However, issues such as this while reworking my app to accommodate the v7 API are giving me reason to re-evaluate.)

**Comment by bengourley** [comment]
Hi @birtles, I thought I'd chime in here as the lead developer on this notifier.

As I'm sure you've seen from the upgrade guide, this major release has been largely about consolidating what our notifiers look like across platforms, making them more consistent and less error prone.

One source of problems that comes up time and again are the flaws associated with having unrestricted mutable state, so one thing we settled on is having a core set of things that have to be set up-front and cannot change for the lifetime of Bugsnag. This reduces the scope of hard to debug problems, such as errors being sent before certain properties have been set, or whether errors should be sent at all.

We understand that this causes friction for our customers, and so please know that we don't make these kinds of changes without due care and attention. I'm sorry that there's not a direct replacement for the way that you were using Bugsnag before V7.

Here's what I would suggest for you:

1. You can use [this API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/version) to get the version synchronously 
2. Send the `installType` as metadata rather than `releaseStage`: `Bugsnag.addMetadata('extension', 'installType', info.installType)` – metadata is a dedicated place for mutable state to live

I hope this sheds a bit more light.

Have a good weekend!

**Comment by birtles** [comment]
Hi Ben,

Thank you for your thoughtful response. Sorry for the delay on mine. I finally succeeded in migrating my project to the v7 API using some of yours and Matt's suggestions ([changeset here if you're curious](https://github.com/birtles/rikaichamp/commit/f05d01083e45fa446b25995f3fe04746268e71d1)).

I must say, such an ambitious API rewrite shows a lot of courage (in the Apple sense of the word). I didn't see any mention of it in the bugsnag newsletter but would appreciate being able to read about breaking changes there in future.

Thanks again.
