### ISSUE TITLE
TypeScript builds failing due to type errors.

### ISSUE THREAD

**Issue by jkearse3** [bugsnag/bugsnag-js#849]
Hi! Today I've came across an issue with one of the projects I'm working on, my TypeScript builds are now failing on a NodeJS project due to some type errors. I've only noticed this happening today, and as of yesterday my builds have been working fine.

Any help would be greatly appreciated!

VERSION: 6.5.2 (@bugsnag/browser, @bugsnag/js, @bugsnag/node)

ERROR:
```
node_modules/@bugsnag/browser/dist/types/bugsnag.d.ts:22:5 - error TS2374: Duplicate string index signature.

22     [key: string]: any;
       ~~~~~~~~~~~~~~~~~~~

node_modules/@bugsnag/node/dist/types/bugsnag.d.ts:24:5 - error TS2374: Duplicate string index signature.

24     [key: string]: any;
       ~~~~~~~~~~~~~~~~~~~

node_modules/@bugsnag/node/dist/types/bugsnag.d.ts:32:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'autoBreadcrumbs' must be of type 'boolean | undefined', but here has type 'void | undefined'.

32     autoBreadcrumbs?: void;
       ~~~~~~~~~~~~~~~

  node_modules/@bugsnag/node/dist/types/bugsnag-core/common.d.ts:7:3
    7   autoBreadcrumbs?: boolean;
        ~~~~~~~~~~~~~~~
    'autoBreadcrumbs' was also declared here.
```

**Comment by jwmerrill** [comment]
It looks like these errors are newly noticed/enforced by typescript 3.9 [release notes](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/).

**Comment by bengourley** [comment]
Hi @jkearse3. As @jwmerrill suggested (very helpfully, thank you 🙏) the TypeScript compiler after the 3.9 update is indeed more strict.

We have published a major version of Bugsnag since the version you are using (current v7.0.2, you are on v6.5.2).

I checked `@bugsnag/js@v7.0.2` against `typescript@3.9.2` and the compiler seems happy. This doesn't surprise me – we substantially revamped the types in the 6->7 upgrade.

My advice would be to upgrade Bugsnag to the latest version. There is an [upgrade guide here](https://github.com/bugsnag/bugsnag-js/blob/next/UPGRADING.md#6x-to-7x), since we made breaking changes to a lot of the API.

If you can't make the Bugsnag upgrade right now (understandable given the amount of changes) I would suggest pinning the TypeScript compiler to v3.8 until such time that you can.

Hope this helps. Cheers.
