### ISSUE TITLE
SetTimeout / RequestAnimationframe are broken ?

### ISSUE THREAD

**Issue by m4n1ok** [bugsnag/bugsnag-js#850]
Hello, 

I'm working on a Shopify project that include bugnsap. 
My setTimout / RequestAnimationFrame are not working after bugsnap is loaded. 

I guess there are some issue with the override of these native methods. 
The bugsnap version loaded is this one https://d2wy8f7a9ursnm.cloudfront.net/v6/bugsnag.min.js

Thanks

**Comment by johnkiely1** [comment]
Hi @m4n1ok.
Would you have a minimal reproduction case that you could share with us?
You can share that here or if you prefer email us privately at support@bugsnag.com.

**Comment by laukstein** [comment]
I'm experiencing same issue on Bugsnag.js v6 (also v6.5.2). Bugsnag shims setTimeout, setInterval, document.addEventListener and document.removeEventListener.
setTimeout randomly sometimes doesn't work. I think it is caused by already in progress native setTimout that after a but is replaced by Bugsnag shim of setTimeout, it likely drops all "in-progress setTimout's).

I think I have issue also with document.addEventListener - sometimes my events are executed only on second time - click, pinterdown, and seems this is caused by Bugsnag.js too.

I'll try to upgrade to latest v7, I doubt about it.

I while ago I moved from sentry.js to bugsnag.js because of same issues on Sentry. 
https://github.com/getsentry/sentry-javascript/issues/2130 https://github.com/getsentry/sentry-javascript/issues/2125 

It is worth to experience added bugs by bug tracking libraries - it should be opposite.

**Comment by laukstein** [comment]
Bugsnag, can you please not do native functions shims? Or at least allow to disable it, maybe by using `autoTrackSessions: false` there is no reason to have shims?

**Comment by mattdyoung** [comment]
Hi @laukstein 

You can prevent Bugsnag from shimming these methods by using the `trackInlineScripts: false` option:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#trackinlinescripts-browser-only

**Comment by laukstein** [comment]
@mattdyoung why this issue was closed? Anything done to fix it?
@m4n1ok, do you have any way to reproduce this issue, any link to example?

**Comment by mattdyoung** [comment]
Bugsnag shims these methods as this is the only reliable way to track inline scripts in order to report the surrounding code and line number when things go wrong.

If this causes issues for your code, you can prevent Bugsnag shimming these methods by using the `trackInlineScripts: false` option:
https://docs.bugsnag.com/platforms/javascript/configuration-options/#trackinlinescripts-browser-only

If you can share a reproduction case demonstrating the issue shimming is causing, we can re-open and investigate whether or not the issue lies with Bugsnag.

**Comment by kith-and-kin** [comment]
You can't do the above within a Shopify theme.
Shopify themselves are injecting bugsnag to the theme - whether you like it or not. It can't be disabled or modified.

When Bugsnag is then loaded it is breaking quite a large amount of functionality by highjacking events as described above.

I've verified this by using the method described here: 
https://github.com/Shopify/slate/issues/1097#issuecomment-660118899

Deferring Bugsnag completely fixes the issue.

From what I can see - bugsnag appears to be being added by Shopify anytime a product video or 3D model is being introduced.
