### ISSUE TITLE
[Vue plugin] Not getting a Vue tab in dashboard.

### ISSUE THREAD

**Issue by guillaumejay** [bugsnag/bugsnag-js#990]
Bugsnag is working and displaying errors, but I don't have a Vue tab in the dashboard

This is  the end of my main.js file
```javascript
Bugsnag.start({ apiKey: '[mykey]', plugins: [new BugsnagPluginVue(Vue)] })
/* Bugsnag.getPlugin('vue').installVueErrorHandler(Vue) */ 
  
new Vue({
  router,
  store,
  render: h => h(App)
}).$mount("#app")
```
The installVueErrorHandler is commented because if I keep it, I get this warning :
bugsnag-vue.js:27 [bugsnag] installVueErrorHandler() was called unnecessarily

and anyway, it changes nothing.  

Bugsnag is greate without this vue tab, of course, but since you're telling me I should have one, I'm curious :)

**Comment by xander-jones** [comment]
Hey @guillaumejay, the Vue tab will only be shown if the error is thrown from a Vue component. I'm not sure how you're throwing a test error in this case, but if you're not seeing the Vue tab, but have the Vue plugin installed, I'd suspect it's because it's not an error coming from a Vue component?

If for example you were to put the following code into one of your `.vue` files:
```js
  <div class="hello">
    <h1>This is going to break.. {{ msg.ohno.thishasnoreference }}</h1>
...
```

You'll see the following error pop up in Bugsnag, which does contain the Vue tab:
![image](https://user-images.githubusercontent.com/9535852/89901217-b4278b80-dbdc-11ea-8c28-40020611bacc.png)

---

> The installVueErrorHandler is commented because if I keep it, I get this warning :
> bugsnag-vue.js:27 [bugsnag] installVueErrorHandler() was called unnecessarily

The call to `installVueErrorHandler()` is only needed if you **_don't_** specify the `Vue` component when you apply the Bugsnag Vue plugin, which you are currently doing.

In essence, you can do either:
```js
Bugsnag.start({ apiKey: 'API_KEY', plugins: [new BugsnagPluginVue(Vue)] })
```

or, lazily install the Vue plugin _later_, once it has initialized.

```js
Bugsnag.start({ apiKey: 'API_KEY', plugins: [new BugsnagPluginVue()] })

// Later, when Vue is loaded and ready...
Bugsnag.getPlugin('vue').installVueErrorHandler(Vue)
```

If you're still experiencing issues, let us know at support@bugsnag.com, and we'll take a look into your configuration to see if we can find why this is not working for you.
